### ISSUE TITLE
SQL statement matching is not case insensitive

### ISSUE THREAD

**Issue by rmcqueen** [dalibo/sqlserver2pgsql#103]
**Brief**: when using this tool, any SQL statements (`CREATE TABLE`, `DROP TABLE`, etc.) which were not entirely uppercased caused the tool to fail.

**Example**:
```
Create TABLE [dbo].[Person] (
    [id] [int] NOT NULL,
    [age] [varchar](5) NOT NULL
) ON [PRIMARY]
```
results in: `> (1) not understood. This is a bug at ./sqlserver2pgsql.pl line 2399, <$file> line 1.`

When resolving the `Create` statement to instead be `CREATE`, it worked just fine:
```
CREATE TABLE [dbo].[Person] (
    [id] [int] NOT NULL,
    [age] [varchar](5) NOT NULL
) ON [PRIMARY]
```

Additionally, modifying the portion of the code which performs a regex match for the `CREATE TABLE` syntax to be case insensitive resulted in no error occurring and a proper converted PostgreSQL file being generated:
```
if ($line =~ /^CREATE TABLE \[(.*)\]\.\[(.*)\]\s*\(/)  { ... }
```
becomes:
```
if ($line =~ /^CREATE TABLE \[(.*)\]\.\[(.*)\]\s*\(/i) { ... }
```

**Summary**:
It appears a case insensitive flag can be applied onto the regex statements to resolve this issue, however, this is just from a naive glance at the code. I haven't spent the time tinkering to see where this would cause other issues.

**Comment by madtibo** [comment]
hello @rmcqueen ,

We are usually using dumps from SQL Server backups. It is much easier to parse since we have less white spaces or case problems.
So yes, a "/i" flag would work... but it might cause problems that we are not thinking about and it would slow down the processing.

Can you propose a PR including an insensitive flag in all regex so we can test the impact?

Cordialement,

**Comment by madtibo** [comment]
The easiest way to get things right would be to import your schema in SQLServer and dump it to feed sqlserver2pgsql script.
I close this issue.

Cordialement,
