### ISSUE TITLE
Question: Which part of code covert type from SQL to PostgreSQL

### ISSUE THREAD

**Issue by manishdwivedi02** [dalibo/sqlserver2pgsql#105]
I used this sqlserver2pgsql.pl script to convert SQL to PostgreSQL schema . In my case, in SQL database some fields are type [nvarchar](max) (that is in SQL DB tables are having field type - nvarchar, having character_maximum_length = -1) in SQL dump text file. This script is converting these fields to varchar for Case Sensitive PostgreSQL conversion from SQL. However I want these fields ([nvarchar](max)) to convert to type – text.

I looked at script to modify the coded, and I am pretty sure conversion is being done in “sub convert_type” function. However I am not able to get which line to change for my requirement. Can you please help me here? Thanks in advance.

**Comment by madtibo** [comment]
Hello @manishdwivedi02 ,
Could you give me the table creation orders from your SQL Server dump?

**Comment by manishdwivedi02** [comment]
Hello @madtibo

Sorry I could not get what you mean by order. Here is example of table extracted from SQL Server dump file. C4 column is [nvarchar](max) and it is getting converted to varchar. However I want C4 as text type in PostgreSQL


/****** Object:  Table [dbo].[T1067]    Script Date: 6/21/2019 12:53:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T1067](
	[C1] [nvarchar](15) NOT NULL,
	[C2] [nvarchar](254) NULL,
	[C3] [int] NOT NULL,
	[C4] [nvarchar](max) NULL,
	[C5] [int] NULL,
	[C6] [nvarchar](128) NULL,
PRIMARY KEY CLUSTERED 
(
	[C1] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

Please let me know if you need more details. Thanks

**Comment by madtibo** [comment]
Changing the types in the %types hash should be sufficient for your use case.
I created a specific branch: https://github.com/dalibo/sqlserver2pgsql/tree/nvarchar2text
Does is suit your need?

Cordialement,

**Comment by manishdwivedi02** [comment]
Changing the types in the %types for nvarchar does not fulfill my requirement, since all nvarchar datatype will get converted to type text. You can drop this branch.

Explaining my case in short (below columns are from Table_Schema.zip attached in my previous reply)

[C2] [nvarchar](254) NULL -> Getting converted as "c2" varchar(254) (this is fine)
[C4] [nvarchar](max) NULL -> Getting converted as "c4" varchar (_this is not fine in my case, only these datatype should be converted to type "text"_)

I see SQL DB tables having field type - nvarchar (having character_maximum_length = -1) are present as **[nvarchar](max)** in generated SQL dump text file.

Yesterday I could modify the perl code at right place and now schema is getting converted as I need. Please find attached "sqlserver2pgsql_updated_v01.zip" updated perl script.

**Added following line of code in "convert_type" function**

# Add on 20190709 - This is one of the few nvarchar types which has character_maximum_length = -1 (that is [nvarchar](max)) in generate scripts from SQL database
if ($sqlstype =~ /varchar/ and not defined $sqlqual) {
	$rettype = "text";
}

You can run original perl script and my updated perl script against sample SQL Dump file (Table_Schema.zip attached in my previous reply) and compare before.sql

[sqlserver2pgsql_updated_v01.zip](https://github.com/dalibo/sqlserver2pgsql/files/3376534/sqlserver2pgsql_updated_v01.zip)

**Comment by madtibo** [comment]
OK, I had not understand your need.
Very good news that you manage to modify it to your need!

The thing is `varchar` (with no size) and `text` types are the same under the hood (varlena). You can check this [depesz article](https://www.depesz.com/2010/03/02/charx-vs-varcharx-vs-varchar-vs-text/) to learn more about it.
Thus, I see no need to update the actual processing.

Cordialement,
