### ISSUE TITLE
Error -> Line not understood

### ISSUE THREAD

**Issue by PJanissen** [dalibo/sqlserver2pgsql#113]
When running the script on my sql file I get the following error:

> Line <ALTER TABLE [dbo].[logMessage] ADD CHECK (logLevel IN('Error', 'Warning', 'Info', 'Debug', 'Audit', 'None')); > (81) not understood. This is a bug at C:\Users\PimJanissen\Documents\GitHub\sqlserver2pgsql\sqlserver2pgsql.pl line 2386, <$file> line 81.

Line 81 in the sql script looks like this: 

> ALTER TABLE [dbo].[logMessage] ADD CHECK (logLevel IN('Error', 'Warning', 'Info', 'Debug', 'Audit', 'None'));

I am running the script on Windows 10 using strawberry-perl-5.30.0.1-64bit

**Comment by madtibo** [comment]
Hello @PJanissen 
There is indeed a problem.
I created a new branch : [113_constraint_not_understood](https://github.com/dalibo/sqlserver2pgsql/tree/113_constraint_not_understood)
Does it solve your issue?

Cordialement

**Comment by madtibo** [comment]
I guess it does  :-)
