### ISSUE TITLE
Time is not supported. Cannot determine the PostgreSQL's datatype corresponding to time

### ISSUE THREAD

**Issue by manjeshpv** [dalibo/sqlserver2pgsql#12]
Cannot determine the PostgreSQL's datatype corresponding to time. This is a bug
 at sqlserver2pgsql.pl line 246
        main::convert_type('time', 7, 'CreatedTime', 'BackOffice.ApplicationGrou
ps', 'undef', 'public') called at sqlserver2pgsql.pl line 956
        main::add_column_to_table('public', 'BackOffice.ApplicationGroups', 'CreatedTime', 'undef', 'time', '(7)', 'undef', 'NULL') called at sqlserver2pgsql.pl
 line 1073
        main::parse_dump() called at sqlserver2pgsql.pl line 2386

**Comment by marco44** [comment]
Hi, I just added support for the time type. I missed it somehow :)

Corrected by 922169e9910ab4c4d7ec07bf6bec0e8ee5eb0861
