### ISSUE TITLE
Ingestion des données problème avec colonne type datetime2 

### ISSUE THREAD

**Issue by fguiet** [dalibo/sqlserver2pgsql#123]
Salut Gilles,

Tout d'abord merci pour ce superbe outil.
Je te remonte un problème que j'ai sur la migration d'une base SQL Server avec des colonnes de type datetime2.
Les tables PG générées sont bien avec le type `timestamp without time zone` cependant l'outil Pentaho plante avec l'erreur ci-dessous lors de l'insertion des données

> Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "songe"."category" ("id", "name", "bypass_status", "codefichier", "fields", "commentaire", "updated", "created", "createdby", "updatedby") VALUES ( 22,  'Documents de mesures InSitu',  NULL,  'CodeInsitu',  'a:1:{i:0;s:4:"file";}',  'Fichiers de résultats de mesures In Situ',  '2014-12-17 16:00:50.000000',  '2014-07-30 14:35:03.000000',  'XXX',  'XXX') was aborted: ERREUR: la colonne « updated » est de type timestamp without time zone mais l'expression est de type character varying

**Workaround** : je change le type `datetime2` en `datetime` dans la base SQL Server

Un point de détail aussi:

```
./sqlserver2pgsql.pl --help

...
-si SQLSERVER_HOST => Ca devrait être SQLSERVER_INSTANCE
...

```

A+
Frederic

**Comment by madtibo** [comment]
Bonjour @fguiet 

Merci pour les retours. Je corrige pour l'option `-si`.

Il y a souvent des problèmes avec les champs de dates. Si ce n'est pas trop tard pour tester, est-ce que l'option `-stringtype_unspecified` permet de corriger ce problème?

Cordialement,

**Comment by fguiet** [comment]
Bonjour @madtibo,

J'ai effectivement réalisé ma migration. Je ne manquerai pas te revenir vers toi sur ce sujet si d'aventure j'ai une nouvelle migration à réaliser.

**Comment by madtibo** [comment]
l'option -si est corrigée.

On reverra pour les champs dates.
