### ISSUE TITLE
Issue while migrating data for date field

### ISSUE THREAD

**Issue by manishdwivedi02** [dalibo/sqlserver2pgsql#124]
Hello

I got error while running ./kitchen.sh to migrate data. My issue seems related to #72 but I could not resolve my issue. Can you please help me for this?

2019/12/09 05:59:58 - SQL SCRIPT START - ERROR (version 8.2.0.0-342, build 8.2.0.0-342 from 2018-11-14 10.30.55 by buildguy) : An error occurred executing this job entry : 
2019/12/09 05:59:58 - SQL SCRIPT START - **Couldn't execute SQL: CREATE CAST (varchar as date) with inout as implicit**
2019/12/09 05:59:58 - SQL SCRIPT START - 
2019/12/09 05:59:58 - SQL SCRIPT START - ERROR: must be owner of type character varying or type date

**Comment by madtibo** [comment]
Hello @manishdwivedi02 

Just to be sure, did you use the "-stringtype_unspecified" when running sqlserver2pgsql.pl?

If yes, can you check that you have the `<attribute><code>EXTRA_OPTION_POSTGRESQL.stringtype<\/code><attribute>unspecified<\/attribute><\/attribute>` string in your ktr files?

Cordialement,

**Comment by manishdwivedi02** [comment]
I tried with option -stringtype_unspecified while running sqlserver2pgsql.pl. I had also checked few ktr files and can see EXTRA_OPTION_POSTGRESQL.stringtype line, but I am still getting same error "Couldn't execute SQL: CREATE CAST (varchar as date) with inout as implicit"

<attribute><code>EXTRA_OPTION_POSTGRESQL.stringtype</code><attribute>unspecified</attribute></attribute>

Just to confirm, I see </code> and </attribute> in string but I see <\/code> & <\/attribute> in your reply. Do I need \ as well.

**Comment by manishdwivedi02** [comment]
I tried with option -stringtype_unspecified while running sqlserver2pgsql.pl. I had also checked few ktr files and can see EXTRA_OPTION_POSTGRESQL.stringtype line, but I am still getting same error "Couldn't execute SQL: CREATE CAST (varchar as date) with inout as implicit"

String in ktr files: - **\<attribute>\<code>EXTRA_OPTION_POSTGRESQL.stringtype\</code>\<attribute>unspecified\</attribute>\</attribute>**

I had also looked the job in spoon to debug the issue. When tried to execute job it failed at "SQL SCRIPT START" step. I see there are 2 steps "SQL SCRIPT START" at start and "SQL SCRIPT END" at end, in job. These steps are having below sql script and looks like causing issue.

**SQL SCRIPT START step sql scripts**
DROP CAST IF EXISTS (varchar as date);
CREATE CAST (varchar as date) with inout as implicit;
ALTER TABLE to DISABLE TRIGGER ALL for each table

**SQL SCRIPT END step sql scripts**
DROP CAST (varchar as date);
ALTER TABLE to ENABLE TRIGGER ALL for each table

**Comment by madtibo** [comment]
I am not a pentaho expert, thus I am not sure how to correct this problem in Pentaho.

The PostgreSQL way to solve your problem would be to assign either the type date or varchar to your migration role during your migration:
`ALTER TYPE varchar OWNER TO <migration_role>;`

Once the migration is done, you can set the type back to normal:
`ALTER TYPE varchar OWNER TO postgres;`

Is it a possible correction for your problem?

**Comment by manishdwivedi02** [comment]
Hello @madtibo 

I had tried both options.
Second option did not work for me, but first option worked. I had used postgres (superuser role) and I could migrate data as well (did not observed error while running pentaho expert job.

Really appreciate your help and quick response
