### ISSUE TITLE
Kettle options...

### ISSUE THREAD

**Issue by dimkadv2** [dalibo/sqlserver2pgsql#125]
Hi!

I'm trying to execute a next command:
`C:\MigrateToPostgres\perl\perl\bin\perl.exe ./sqlserver2pgsql.pl -b before.sql -a after.sql -u unsure.sql  -f script.sql -snake_case ./sqlserver2pgsql.pl -k C:\MigrateToPostgres Portal -sh myserver -sp myPort -su myLogin -sw myPassword -pd portal_test -ph localhost -pp 5432 -pu postgres`

but nothing happens

if i execute the command 
`
C:\MigrateToPostgres\perl\perl\bin\perl.exe ./sqlserver2pgsql.pl -b before.sql -a after.sql -u unsure.sql  -f script.sql -snake_case
` then files are created successfully

what am I doing wrong?
thanks

**Comment by madtibo** [comment]
Hello @dimkadv2 

In your first command, it seems you specify 2 times the `./sqlserver2pgsql.pl` command, is the following command functional?

```
C:\MigrateToPostgres\perl\perl\bin\perl.exe ./sqlserver2pgsql.pl -b before.sql -a after.sql -u unsure.sql -f script.sql -snake_case -k C:\MigrateToPostgres Portal -sh myserver -sp myPort -su myLogin -sw myPassword -pd portal_test -ph localhost -pp 5432 -pu postgres
```

**Comment by dimkadv2** [comment]
Hi, yes, I made a mistake when copying, but the correction did not bring results, files are not created

**Comment by dimkadv2** [comment]
Hi!
The problem was solved by installing pearl. With portable version - problem

Thanks
