### ISSUE TITLE
Cannot Understand Error + ARITHABORT OFF warning 

### ISSUE THREAD

**Issue by ezesande** [dalibo/sqlserver2pgsql#126]
I executed 

./sqlserver2pgsql.pl -f dump.sql -b before -a after -u unsure 

and got the following output:

WARNING: the source database is set as ARITHABORT OFF.
         It means that for SQL Server, 10/0 = NULL.
         You'll probably have problems porting that to PostgreSQL.
Cannot understand ) ON [Data Filegroup 1] TEXTIMAGE_ON [Data Filegroup 1]

 at ./sqlserver2pgsql.pl line 1581, <$file> line 5186.
        main::parse_dump() called at ./sqlserver2pgsql.pl line 3173  

Is the warning related to the error? How can I fix it?

**Comment by madtibo** [comment]
Hello @ezesande 
The warning is not related to the error.
It seems there is an unrecognised SQL command in your script on line 5186 (`) ON [Data Filegroup 1] TEXTIMAGE_ON [Data Filegroup 1]`).
Can you give me the SQL block that includes this command so I can look into it?

**Comment by ezesande** [comment]
It appears several times (67) in the .sql file.

Here there is an example:

CREATE TABLE [dbo].[SANDETEL$Warehouse Receipt Header](
	[timestamp] [timestamp] NOT NULL,
	[No_] [nvarchar](20) NOT NULL,
	[Location Code] [nvarchar](10) NOT NULL,
	[Assigned User ID] [nvarchar](50) NOT NULL,
	[Assignment Date] [datetime] NOT NULL,
	[Assignment Time] [datetime] NOT NULL,
	[Sorting Method] [int] NOT NULL,
	[No_ Series] [nvarchar](10) NOT NULL,
	[Zone Code] [nvarchar](10) NOT NULL,
	[Bin Code] [nvarchar](20) NOT NULL,
	[Document Status] [int] NOT NULL,
	[Posting Date] [datetime] NOT NULL,
	[Vendor Shipment No_] [nvarchar](35) NOT NULL,
	[Cross-Dock Zone Code] [nvarchar](10) NOT NULL,
	[Cross-Dock Bin Code] [nvarchar](20) NOT NULL,
	[Create Posted Header] [tinyint] NOT NULL,
	[Receiving No_] [nvarchar](20) NOT NULL,
	[Last Receiving No_] [nvarchar](20) NOT NULL,
	[Receiving No_ Series] [nvarchar](10) NOT NULL,
 CONSTRAINT [SANDETEL$Warehouse Receipt Header$0] PRIMARY KEY CLUSTERED 
(
	[No_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = ON, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [Data Filegroup 1]
) ON [Data Filegroup 1]
GO
/****** Object:  Table [dbo].[SANDETEL$Warehouse Receipt Line]    Script Date: 27/02/2020 12:33:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

Trying different things I found that maybe the error could be related to the line breaks inserted by  SQL Server Management Studio. Still couldn´t find a solution.

**Comment by madtibo** [comment]
Hello @ezesande 

There was indeed a problem with the partition_scheme or filegroup that was not "PRIMARY".
This should be solved now.

Can you validate the correction?
