### ISSUE TITLE
Don't know what to do with this extendedproperty

### ISSUE THREAD

**Issue by farhanmasud** [dalibo/sqlserver2pgsql#129]
Hi,

I'm getting this error that has something to do with extendedproperty. I have checked out [#59](https://github.com/dalibo/sqlserver2pgsql/issues/59) but this one is probably different.

`Don't know what to do with this extendedproperty: EXEC sys.sp_addextendedproperty @name=N'AggregateType', @value=N'-1' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CopySiteLocation', @level2type=N'COLUMN',@level2name=N'SiteLocationID'
 at C:\Users\LENOVO\Downloads\sqlserver2pgsql\sqlserver2pgsql.pl line 2292, <$file> line 995.
        main::parse_dump() called at C:\Users\LENOVO\Downloads\sqlserver2pgsql\sqlserver2pgsql.pl line 3173`

[SQL dump](https://github.com/dalibo/sqlserver2pgsql/files/4814737/script-clearweb-schema-tables.zip)

**Comment by madtibo** [comment]
Hello @farhanmasud 
I could not find much informations about the extended properties in your file:
```
AggregateType, AllowZeroLength, AppendOnly, Attributes, CollatingOrder, ColumnHidden, ColumnOrder, ColumnWidth, DataUpdatable, DateCreated, DefaultValue, DisplayViewsOnSharePointSite, FilterOnLoad, GUID, HideNewField, LastUpdated, MS_DecimalPlaces, MS_DefaultView, MS_DisplayControl, MS_Format, MS_Hyperlink, MS_IMEMode, MS_IMESentMode, MS_InputMask, MS_OrderByOn, MS_Orientation, Name, OrderByOnLoad, OrdinalPosition, RecordCount, Required, ShowDatePicker, Size, SourceField, SourceTable, TextAlign, TextFormat, TotalsRow, Type, UnicodeCompression, Updatable
```

Which tool did you used to create this schema? is the code coming from access?

**Comment by madtibo** [comment]
I pushed a correction to ignore all your extended properties.
Can you give it a try?

You have illegal Unicode characters in your dump. sqlserver2pgsql gives you the line when complaining, just delete the given characters. And it will works.

**Comment by farhanmasud** [comment]
Hi @madtibo,

Thank you very much for going through this, it's working perfectly now!

The SQL dump was created using SQL Server Management Studio 12 for a MSSQL database.

**Comment by madtibo** [comment]
You're welcome.
Have fun with PostgreSQL!!
:)

**Comment by farhanmasud** [comment]
Absolutely! Thanks again for taking the time for helping me with the issue :)

Closing this since it's fixed.
