### ISSUE TITLE
Strategy to apply when the migration is to be done with schema/data update?

### ISSUE THREAD

**Issue by sebpcspkr** [dalibo/sqlserver2pgsql#13]
Hello,
I really appreciate the migration tool.
I am facing a situation which isn't exactly the purpose of the tool : I have DBs in Microsoft SQLServer and I want to migrate them into Postgresql, but I have changes into data definitions at the same time (I know it is'nt the "best pratices" way).
Would you advice me to use the tools even in this situation? 
And if this is the case, have you some kind of manner to do this?
If you have, I think it should be interesting to add documentation about.

**Comment by marco44** [comment]
I cannot really advise you on the best way for you to do it.

But as far as I'm concerned, that's the reason I developped the tool that way: I can add whatever I want to my migration job, as Kettle is a very feature-rich ETL.

You can use sqlserver2pgsql to generate a sql script for the new schema, and a Kettle script for the data, and then edit both. You change the SQL script, then use Kitchen (kettle's GUI) to add your transforms on the way from SQL Server to PostgreSQL. The tool already does that for a few datatypes, for instance to remove the '\0's from SQL Server's strings when inserting them into PostgreSQL (as they are forbidden).

I'd really like to add some documentation about this, but I think this would amount to writing a Kettle tutorial, when theirs are already quite good :)

I could add a FAQ item about this though.

**Comment by sebpcspkr** [comment]
Quick and nice answer : the FAQ seems to be the place.
Now I have to enter into the Kettle world :)
Thanks

**Comment by marco44** [comment]
Yup. A big investment at the beginning. But you'll be very happy you've done it, it saved me weeks of work sometimes :)

**Comment by marco44** [comment]
60fe3c83765e6f11e1ebd01de68ed9f8e297c6b2
