### ISSUE TITLE
Stored procedure/ functions migration

### ISSUE THREAD

**Issue by sidtandon2014** [dalibo/sqlserver2pgsql#130]
Is Stored procedure/ functions migration also supported?

**Comment by madtibo** [comment]
Hello @sidtandon2014 

I completely missed your issue during the summer.

As it is explain in the [FAQ document](https://github.com/dalibo/sqlserver2pgsql/blob/master/FAQ.md):
> No, Transact-SQL is very different from PostgreSQL's many PL languages. These would need a manual migration.
