### ISSUE TITLE
INCLUDE columns in indexes supported since postgresql 11

### ISSUE THREAD

**Issue by mikes-gh** [dalibo/sqlserver2pgsql#131]
https://github.com/dalibo/sqlserver2pgsql/blob/7e65e475eddb4ff58cdd7ede80074bc0d9981b54/sqlserver2pgsql.pl#L1939

since postgresql version 11 this is supported.

I do have a couple in my migration but understand if this is low priority.
Probably a simple fix though

**Comment by madtibo** [comment]
Hello @mikes-gh 

Just to be sure about the SQL Server grammar, could you give me the original DDL to create the index with INCLUDE columns? 

Cordialement,

**Comment by madtibo** [comment]
Thank you for the script.

Here (#132) is a first version for parsing included columns. Does it work for you?

**Comment by madtibo** [comment]
Branch #132 merged in master.

Several PR have been merged last week. Tell me if this is still fine for you.

**Comment by mikes-gh** [comment]
All good as of 898044b5128cffafac100f17c68bf071541df072
Ran a couple of imports since.

**Comment by madtibo** [comment]
Great!  
Thank you for the tests :-)

I'm closing this issue.
