### ISSUE TITLE
add the ability to denormalize varchar/text (instead of using citext extension)?

### ISSUE THREAD

**Issue by sebpcspkr** [dalibo/sqlserver2pgsql#14]
Hello,

To avoid  the use of citext extension (FAQ), I suggest you to add an option to provide denormalizing functionnality for varchar/text columns.

Here's an implementation example:
For a source column named column_a you will have a final denormalized column (upper for example) with the same name (column_a ) and the original data stored into column_a_initial_col.
This implies too adding a trigger when inserting into column_a (insert true value in column_a_initial_col, insert upper value in column_a) / idem in updating / idem in deleting.

Do you think it's something that should be added?

**Comment by marco44** [comment]
It seems a bit weird. Adding a column maintained by the trigger will be even slower thar citext. And it will require you to rewrite your app to use sometimes the column maintained by a trigger, and other times the original column.

Do you have a usecase which would make it clearer for me ?

**Comment by sebpcspkr** [comment]
No usecase. I only try to find a method to avoid citext "automatically"...but I didn't know this manner was worst :)

**Comment by marco44** [comment]
The only other thing I can think of, is teaching PostgreSQL to also have case-insensitive collations. But that's another level of complexity :)

**Comment by marco44** [comment]
Closing it. If you find a clever way to deal with is, you can reopen it.
