### ISSUE TITLE
Problem with datetime2 conversion

### ISSUE THREAD

**Issue by mjrosenberg** [dalibo/sqlserver2pgsql#142]
I am trying to convert my schema and it is throwing an error when it gets to a datetime2 conversion. The specific error is as follows: Cannot understand 	[ValidFrom] [datetime2](0) GENERATED ALWAYS AS ROW START NOT NULL,

 at sqlserver2pgsql.pl line 1580, <$file> line 483.

I am fairly new to this, so I'm a bit stuck on how to fix the issue. It is not generating any table conversion currently as it stops at the line I'm getting an error on

**Comment by madtibo** [comment]
Bonjour @mjrosenberg 

I am not sure the problem arises from the datetime2 field... It might come from the end of the line with the generated column.

Could you give me the table definition so I can test it?

Cordialement,

**Comment by madtibo** [comment]
I close this issue. 
Do not hesitate to reopen it if you still experience your problem.
