### ISSUE TITLE
Error converting nvarchar(max) in table-type

### ISSUE THREAD

**Issue by mesztam** [dalibo/sqlserver2pgsql#143]
Hi,

I get the error "Cannot understand      ` [Test1] [nvarchar](max) NULL`" when trying to convert this user defined table type:
```
CREATE TYPE [dbo].[UDT_Test] AS TABLE(
	[Test1] [nvarchar](max) NULL
)
```

The nvarchar(max) seems to be handled in normal tables, but not in table types. Can you please help?

regards,
Tamas

**Comment by madtibo** [comment]
Hello @mesztam 

The max was indeed not waited for in the CREATE TYPE parsing. 
Does the patch in this branch https://github.com/dalibo/sqlserver2pgsql/pull/145 solve your problem?

Cordialement,

**Comment by mesztam** [comment]
Hello, yes, it does solve it, thanks a lot!

I'm not sure if it is related to this patch, but now I receive plenty of warnings like this:

Use of uninitialized value $typequal in string eq at sqlserver2pgsql.pl line 1833, <$file> line 93.
Use of uninitialized value $typequal in string eq at sqlserver2pgsql.pl line 1833, <$file> line 99.
Use of uninitialized value $typequal in string eq at sqlserver2pgsql.pl line 1833, <$file> line 104.
Use of uninitialized value $typequal in string eq at sqlserver2pgsql.pl line 1833, <$file> line 105.
Use of uninitialized value $typequal in string eq at sqlserver2pgsql.pl line 1833, <$file> line 106.
Use of uninitialized value $typequal in string eq at sqlserver2pgsql.pl line 1833, <$file> line 107.

regards,
Tamas

**Comment by madtibo** [comment]
It is indeed related, thanks for the test  :-)

I'll update the patch to correct that.

**Comment by madtibo** [comment]
It should be corrected. Can you give it a try?

**Comment by mesztam** [comment]
Works perfectly, thanks a lot!

**Comment by madtibo** [comment]
Thank you. The PR is merged.
