### ISSUE TITLE
Errors with data importing

### ISSUE THREAD

**Issue by naveenjul29** [dalibo/sqlserver2pgsql#144]
**I executed the below command:**

perl sqlserver2pgsql.pl -nr -f my_Script.sql -b my_before_script -a my_after_script -u my_unsure_script -k /home/test/sqlserver2pgsql/output -sh SQLIP -sp 1433 -sd SQLDB -su SQLUser -sw SQLPWD -pd PostgresDB -ph PostgresIP -pp 5432 -pu puser -pw Ppwd

**I got the below errors and it stopped the execution. I also used -use_pk_if_possible=0 but no luck**

dbo/table1 has no PK. Cannot create an incremental transformation
dbo/table2 has no PK. Cannot create an incremental transformation
dbo/table3 has no PK. Cannot create an incremental transformation
dbo/table4 has no PK. Cannot create an incremental transformation
dbo/table5 has no PK. Cannot create an incremental transformation
dbo/table6 has no PK. Cannot create an incremental transformation

**Please help me on migrating the data from SQLServer PostgreSQL**

**Comment by madtibo** [comment]
Hello @naveenjul29 

These messages are more warnings to tell you that it will not be possible to use incremental job to migrate your data.

If some tables have no primary key, it will not be possible to use incremental transformation. But there should be no problem to use the classic job kettle to migrate your data.

Cordialement,

**Comment by naveenjul29** [comment]
Thank you for your quick response. I really appreciate it.

But, when I run the above command, the execution is stopped with those warnings. I am really not sure how to proceed further.

can you please guide me on migrating the data(if possible step by step) from SQL Server to PostgreSQL?

Thank you so much in advance.

**Comment by madtibo** [comment]
The operation is documented in <https://github.com/dalibo/sqlserver2pgsql/blob/master/FAQ.md>

Could you check that your sql files are complete (before.sql, after.sql and unsure.sql)?  
Then can you try to migrate your data using the kjb files?

**Comment by naveenjul29** [comment]
Thank you for quick response.

yes, my SQL files(before.sql, after.sql and unsure.sql) are completed.

can you please help me with the steps to create kettle jobs to migrate the data (migration.kjb)?

**Comment by naveenjul29** [comment]
can someone please help me on this?

**Comment by madtibo** [comment]
Hello @naveenjul29 

To generate the kettle jobs, you need to specify several parameters:
```
  Kettle options: 
    if you are generating for kettle, you must provide connection information.

    -k KETTLE_OUTPUT_DIRECTORY

    -sd SQLSERVER_DATABASE
    -sh SQLSERVER_HOST
    -si SQLSERVER_INSTANCE
    -sp SQLSERVER_PORT
    -su SQLSERVER_USERNAME
    -sw SQLSERVER_PASSWORD
    -pd POSTGRESQL_DATABASE
    -ph POSTGRESQL_HOST
    -pp POSTGRESQL_PORxT
    -pu POSTGRESQL_USERNAME
    -pw POSTGRESQL_PASSWORD
    -pi PARALLELISM_IN
            parallelism level for the kettle job (input, SQL Server). Default 1.
    -po PARALLELISM_OUT
            parallelism level for the kettle job (output, PostgreSQL). Default 8.
    -stringtype_unspecified
            By default, the data are sent as varchar. This can block date field
            migration. By using this option, make PostgreSQL infer the data type.
```

Cordialement,

**Comment by naveenjul29** [comment]
I executed the below command:

perl sqlserver2pgsql.pl -nr -f my_Script.sql -b my_before_script -a my_after_script -u my_unsure_script -k /home/test/sqlserver2pgsql/output -sh SQLIP -sp 1433 -sd SQLDB -su SQLUser -sw SQLPWD -pd PostgresDB -ph PostgresIP -pp 5432 -pu puser -pw Ppwd

got the below warnings:

WARNING: fk_geofencetypealertmanagementassociated_geofencetypealertmanagementassociated is more than 63 characters long; PostgreSQL will truncate the name internally

Important WARNING: You have to set up KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL=Y in /home/qmigsql/.kettle/kettle.properties.
If this file doesn't exist yet, start spoon from the kettle directory once.Cannot create /kettle_output at sqlserver2pgsql.pl line 844.

**I didn't find kettle.properties file so started spoon and below is the output**

#######################################################################
WARNING:  no libwebkitgtk-1.0 detected, some features will be unavailable
    Consider installing the package with apt-get or yum.
    e.g. 'sudo apt-get install libwebkitgtk-1.0-0'
#######################################################################
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
	at org.eclipse.swt.SWT.error(SWT.java:4621)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1038)
	at org.eclipse.swt.widgets.Display.create(Display.java:1025)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:179)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:590)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:581)
	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:668)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)

**Note: before.sql, after.sql and unsure.sql files are created successfully. Kettle job is not generated to migrate the data.**

Please suggest me further on this.

**Comment by naveenjul29** [comment]
can someone please help me?

**Comment by naveenjul29** [comment]
please help me troubleshooting the issue further.

**Comment by naveenjul29** [comment]
I executed the below command:

perl sqlserver2pgsql.pl -nr -f my_Script.sql -b my_before_script -a my_after_script -u my_unsure_script -k /home/test/sqlserver2pgsql/output -sh SQLIP -sp 1433 -sd SQLDB -su SQLUser -sw SQLPWD -pd PostgresDB -ph PostgresIP -pp 5432 -pu puser -pw Ppwd

got the below warnings:

WARNING: fk_geofencetypealertmanagementassociated_geofencetypealertmanagementassociated is more than 63 characters long; PostgreSQL will truncate the name internally

Important WARNING: You have to set up KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL=Y in /home/qmigsql/.kettle/kettle.properties.
If this file doesn't exist yet, start spoon from the kettle directory once.Cannot create /kettle_output at sqlserver2pgsql.pl line 844.

I didn't find kettle.properties file so started spoon and below is the output

#######################################################################
WARNING: no libwebkitgtk-1.0 detected, some features will be unavailable
Consider installing the package with apt-get or yum.
e.g. 'sudo apt-get install libwebkitgtk-1.0-0'
#######################################################################
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
at org.eclipse.swt.SWT.error(SWT.java:4621)
at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1038)
at org.eclipse.swt.widgets.Display.create(Display.java:1025)
at org.eclipse.swt.graphics.Device.(Device.java:179)
at org.eclipse.swt.widgets.Display.(Display.java:590)
at org.eclipse.swt.widgets.Display.(Display.java:581)
at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:668)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)

Note: before.sql, after.sql and unsure.sql files are created successfully. Kettle job is not generated to migrate the data.

Please suggest me further on this.

**Comment by madtibo** [comment]
Hello @naveenjul29 

It seems there is a problem with the kettle output directory. You specified the following directory: "/home/test/sqlserver2pgsql/output". Does this directory exist? If yes does your user have the correct rights?

You should try to start kettle to create a configuration file. If you had, edit the /home/qmigsql/.kettle/kettle.properties file and add the following line in it:
```
KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL=Y
```

You should as well try to install the following package:
```
sudo apt-get install libwebkitgtk-1.0-0
```

Cordialement,

**Comment by madtibo** [comment]
I close this issue. 
Do not hesitate to reopen it if you still experience your problem.
