### ISSUE TITLE
sqlserver2pgsql fails when using empty password for connections in conf file

### ISSUE THREAD

**Issue by sebpcspkr** [dalibo/sqlserver2pgsql#15]
Hello
When using empty password for connections in conf file, the scripts return error 1 with message:
"You have to provide all connection information, if using -k or kettle directory set in configuration file".

To avoid this, I put sqlserver password="", and it runs ok. But the generated kettle files are then false : they contain <password>""</password> instead of <password></password>. I correct them with a 'sed -i'.

Maybe a note should be added about empty password...I know it's not the normal use but it exists (in dev environment).

:)

**Comment by marco44** [comment]
If the password is empty (you mean authentication is trust ?) you can put whatever you like in the password field. And as far as I remember, the password isn't an option in kettle's gui.

**Comment by sebpcspkr** [comment]
the sqlserver password is empty.
The generated .ktr files cointained <password>""</password> and the kitchen command failed.
When the modified .ktr files contain <password></password> (after the sed), the kitchen command runs ok...

**Comment by sebpcspkr** [comment]
Sorry : github doesn't like &lt; and &gt; so I think my last messages where not clear! (Sanitization)
I write again whith htmlencoding:
the sqlserver password is empty.
The generated .ktr files cointained &lt;password&gt;""&lt;/password&gt; and the kitchen command failed.
When the modified .ktr files contain&lt;password&gt;&lt;/password&gt; (after the sed), the kitchen command runs ok...

**Comment by marco44** [comment]
Ok. I keep this one open, I'll give it a look when I have time. For now, you can just put 'foo' as your password, it should work OK.

**Comment by sebpcspkr** [comment]
I submitted Pull Request #16 ... with this, it's fixed! Thanks.
