### ISSUE TITLE
Empty string, empty guess at ./sqlserver2pgsql.pl line 1434.

### ISSUE THREAD

**Issue by jackerzhou** [dalibo/sqlserver2pgsql#157]
my $decoder = guess_encoding($data, qw/iso8859-15/);

**Comment by madtibo** [comment]
Hello @jackerzhou 

Does the problem come from your dump file encoding?
Is it in UTF-16? In an other encoding?

Cordialement,

**Comment by madtibo** [comment]
I close this issue. 
Do not hesitate to reopen it if you still experience your problem.

**Comment by slieer** [comment]
utf8 or iso-8859-15 at ./sqlserver2pgsql.pl line 1506.
