### ISSUE TITLE
Import data from sql server to postgresql

### ISSUE THREAD

**Issue by melwin789** [dalibo/sqlserver2pgsql#158]
Hi,
I tried your utility and it worked well but it did not convert insert statements which where present in my script which I needed to convert.

Also wanted to know the procedure to install Kettle the link to where the file I can get without login and the steps to make it work in windows.

Thanks.

**Comment by beaud76** [comment]
Nice to ear that the generated DDL works well. Regarding non SQL statements like INSERT, they are not supposed to be converted by the tool. But you should easily find some online tools that help translating SQL from sqlserver to postgres.

About Kettle, I have not the required knowledge to answer you, and no Windows machine to test. Sorry. May be someone else could help ?
