### ISSUE TITLE
schema-level comments are not supported

### ISSUE THREAD

**Issue by spanevin** [dalibo/sqlserver2pgsql#162]
schema-level comments are not supported (when only @level0type and @level0name parameters are specified)

like
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'schema description' , @level0type=N'SCHEMA',@level0name=N'SchemaName'

Actually, all parameters of sys.sp_addextendedproperty are optional (= NULL) except @name, but it's reasonable to ignore calls with no @level0type and @level0name...

I'll try to provide a patch, I have updated version already.

**Comment by spanevin** [comment]
No idea how to create a branch for an issue...

Attaching updated file with proposed fix.
[sqlserver2pgsql.zip](https://github.com/dalibo/sqlserver2pgsql/files/9101210/sqlserver2pgsql.zip)

**Comment by spanevin** [comment]
Created a pull request, https://github.com/dalibo/sqlserver2pgsql/pull/163

**Comment by beaud76** [comment]
Thank You very much for having reported the point and for your proposal.
I just have just merged your PR.
