### ISSUE TITLE
DateTimeOffset

### ISSUE THREAD

**Issue by biggosh** [dalibo/sqlserver2pgsql#17]
Hi,

I tried the script on my sql server dump and this error is output:

Cannot determine the PostgreSQL's datatype corresponding to datetimeoffset. This is a bug
 at ./sqlserver2pgsql.pl line 247
	main::convert_type('datetimeoffset', 7, 'CreatoIl', 'SYS_Stati', undef, 'public') called at ./sqlserver2pgsql.pl line 957
	main::add_column_to_table('public', 'SYS_Stati', 'CreatoIl', undef, 'datetimeoffset', '(7)', undef, 'NULL') called at ./sqlserver2pgsql.pl line 1074
	main::parse_dump() called at ./sqlserver2pgsql.pl line 2389

Starting db is on a SQL2008R2 

Thanks

**Comment by marco44** [comment]
Hi,

It seems datetimeoffset is simply a timestamp with time zone. I just added support. Can you confirm it works ?

Regards

**Comment by marco44** [comment]
Oh, by the way, if you are also doing the data migration with Kettle, please check that the time offsets are kept.

**Comment by biggosh** [comment]
Perfect. It works!
I'm not using kettle to migrate data and so I cannot check. I use OpenTalend for data migration and integration.

Thanks
