### ISSUE TITLE
Wrong CREATE SEQUENCE for Primary Key

### ISSUE THREAD

**Issue by buiducnhat** [dalibo/sqlserver2pgsql#170]
After run the `sqlserver2pgsql` script, I got some lines like this in `after.sql` file:
```sql
CREATE SEQUENCE "public"."table_name" INCREMENT BY 1 START WITH 1 OWNED BY "public"."table_name"."Id";
```
So after inserting the data to new database, I cannot insert a row with automatically increasing `Id` (PK) because it will insert with `Id = 1` (dupplicated with the data before).

Help you can fix this solution, thank you <3

**Comment by beaud76** [comment]
It is normal that a sequence is created with a start value set to 1. It's the data copy processing that has to manage the current  value setting, depending on the sequence state on the source database.
This can be done by executing a SELECT setval() for each sequence, using the current value on the source database. Alternatively it can use a computed max(column) if the sequence is linked to a specific column with a GENERATED AS IDENTITY clause in a CREATE TABLE statement.

**Comment by beaud76** [comment]
Close issue.
