### ISSUE TITLE
http://kettle.pentaho.com/ .

### ISSUE THREAD

**Issue by elyelyelydevv** [dalibo/sqlserver2pgsql#171]
http://kettle.pentaho.com/ redirect me to https://community.hitachivantara.com/home
how i download "kettle"

**Comment by fljdin** [comment]
Hello there,

Pentaho Data Integration (PDI) is the new Kettle.

* The community documentation is available on [Atlassian](https://pentaho-community.atlassian.net/wiki/spaces/EAI/overview?homepageId=363267360).
* An [entire tutorial](https://pentaho-community.atlassian.net/wiki/spaces/EAI/pages/371557269/Pentaho+Data+Integration+Kettle+Tutorial) points out the PDI Community Edition software on [Sourceforge.net](http://sourceforge.net/projects/pentaho/files/Data%20Integration/).

Regards, Florent
