### ISSUE TITLE
All Table names convert's to lower case

### ISSUE THREAD

**Issue by cowabunga1** [dalibo/sqlserver2pgsql#19]
In my Scheme table names uses CamelCase, script convert it to lowercase. What problem?

**Comment by cowabunga1** [comment]
-keep_identifier_case tells $0 to keep the case of sql server database objects (not advised). Default is to lowercase everything.

now all ok =)

**Comment by marco44** [comment]
Yeah. It's just that it is boring as hell to handle a CamelCase database (at least with PostgreSQL or Oracle), as you have to double quote every identifier (as specified by the SQL standard if y remember correctly). That's why lowercasing everything is the default :)
