### ISSUE TITLE
KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL=Y is tricky

### ISSUE THREAD

**Issue by sebpcspkr** [dalibo/sqlserver2pgsql#23]
Hello again !
The sqlserver2pgsql.pl script checks the Kettle 's conf line containing
/KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL\s*=\s*Y/

But Kettle itself seems to recognize only /^KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL=Y$/
I met a problem with a space after the Y, the propertie wasn't taken into account and it fails with "ERREUR: une valeur NULL viole la contrainte NOT NULL de la colonne xxxx »" .
I dropped the ending space and then it was OK.

So I suggest you to modify the script ton take this into account  :)

Bye

**Comment by marco44** [comment]
Corrected by aa75e4bd131072b18dfd0839208023e8b63f1395
