### ISSUE TITLE
Cannot understand       [CSGUID] [uniqueidentifier] ROWGUIDCOL  NOT NULL,

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [dalibo/sqlserver2pgsql#24]
When running sqlserver2pgsql.pl I'm getting the error message provided in the title of the issue.

If necessary, I can provide the SQL Server dump file.  It has a size of 700 kb.

**Comment by marco44** [comment]
Yes, I need your dump, I'll add it to my regression testing.

Please send me a link to it, to cousinmarc@gmail.com.

Regards.

**Comment by DavidPerezIngeniero** [comment]
Thanks Marco.  Already sent it by email!

**Comment by marco44** [comment]
Committed a few fixes to manage your dump: b629aee74b81fe8aa7f82ee0616635dedbefa5c4

Please tell me if it works

**Comment by DavidPerezIngeniero** [comment]
It works much better than before.

At least, it generates now all the script files with no warning nor error.

Thanks!

**Comment by marco44** [comment]
On Friday 10 July 2015 04:24:18 David P�rez Carmona wrote:
> It works much better than before.
> 
> At least, it generates now all the script files with no warning nor error.
> 
> Thanks!

Ok. If you have the possibility, can you find what this ROWGUIDCOL is used for 
?

**Comment by DavidPerezIngeniero** [comment]
You know more about SQL Server than me, but I would say that it is a column datatype.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms697576(v=vs.100).aspx

CSGUID=Connector space GUID, for geo spatial databases.
