### ISSUE TITLE
ARITHABORT setting

### ISSUE THREAD

**Issue by egbutter** [dalibo/sqlserver2pgsql#25]
Hi @dalibo - Thanks for this great script.  It's been very useful. 

One recommendation: the MSSQL ARITHABORT setting, which terminates queries when  there's an overflow/divide by zero error, is not handled.  Since postgres naturally fails on these errors already, this probably only needs a simple warning logger message. 

Let me know if you want a pull request .. might be easier for you guys to just do it, since this is so simple.  Thanks again,

**Comment by marco44** [comment]
Hi,
Good idea. I'll add this.

Regards

**Comment by marco44** [comment]
Oh, by the way do you have a SQL server schema i could test on ?

**Comment by marco44** [comment]
I'm trying to understand what this would imply. Should we react if ARITHABORT is set to OFF ? (meaning that there are probably very ugly things in the client code or the Transact-SQL)

**Comment by marco44** [comment]
Hi, could you comment on this ?

Regards

**Comment by egbutter** [comment]
Hi @marco44 sorry for the slow reply .. I'll make a simple example and post.

**Comment by egbutter** [comment]
Here's a quick overview of ARITHABORT .. https://msdn.microsoft.com/en-us/library/ms190306.aspx

This is a stupid setting to turn on .. but for legacy reasons we had it turned on for one of our databases.

https://gist.github.com/egbutter/c500ff6276c66c9ba4aa

**Comment by egbutter** [comment]
Yes, the non-default setting is ARITHABORT=OFF.  It also implies that ANSI_WARNINGS=OFF. It's not a big deal - but having it in the dump does cause your script to barf. I recommend you just log that they are using this non-default setting, warn the user, and skip it. Having the setting OFF means the user expects, e.g., 100/0 == null. Both SQL Server and Postgres suggest you to not do this. We have a legacy numerical application that wanted to quickly write a bunch of grid calculations to the database without needing to manage results like infinity, etc.  It's a rare setting, and anyone that has it turned off should know why, and manually fix it during their migration IMHO.

**Comment by marco44** [comment]
Just tell me if this seems OK to you.

I had to manage this in PostgreSQL too once. It needs one to create a new divide function (in C, as you need to be fast), and modify the / operator in the system catalogs to use it.

**Comment by egbutter** [comment]
That looks perfect. Thanks again for sharing this - it saved me a lot of time.

**Comment by marco44** [comment]
You're welcome. Thanks for your feedback.
