### ISSUE TITLE
Error when converting sql_variant data type column

### ISSUE THREAD

**Issue by robotfoot** [dalibo/sqlserver2pgsql#27]
Hi,

Just tried to run the script (table structure only). It looks like it barfed on attempting to convert a sql_variant data type

Cannot determine the PostgreSQL's datatype corresponding to sql_variant. This is a bug
 at C:\Users\Will\Downloads\dalibo-sqlserver2pgsql-d1ef8b7\dalibo-sqlserver2pgsql-d1ef8b7\sqlserver2pgsql.pl line 264, <$file> line 193.
        main::convert_type("sql_variant", undef, "Value", "ActualProp_EquipmentActual", undef, "public") called at C:\Users\Will\Downloads\dalibo-sqlserver2pgsql-d1ef8b7\dalibo-sqlserver2pgsql-d1ef8b7\sqlserver2pgsql.pl line 983
        main::add_column_to_table("public", "ActualProp_EquipmentActual", "Value", undef, "sql_variant", undef, undef, "NULL") called at C:\Users\Will\Downloads\dalibo-sqlserver2pgsql-d1ef8b7\dalibo-sqlserver2pgsql-d1ef8b7\sqlserver2pgsql.pl line 1103
        main::parse_dump() called at C:\Users\Will\Downloads\dalibo-sqlserver2pgsql-d1ef8b7\dalibo-sqlserver2pgsql-d1ef8b7\sqlserver2pgsql.pl line 2444

**Comment by marco44** [comment]
Hi,

Just when I thought I couldn't see a weirder datatype coming from SQL Server… :)

This type isn't supported yet in sqlserver2pgsql. There is no equivalent datatype in PostgreSQL: anyelement/anyarray can only be used in functions. Data in tables should be typed, at least that is how PostgreSQL developpers see it…

If you have any idea about what I could convert it to… maybe just issue a warning and convert it to text, and store it as is. What do you think ?

**Comment by marco44** [comment]
I did just that. sql_variant is converted to text, and a warning message is displayed. There may be some work to be done with the kettle plart, but I don't have data to test on. d8ca1fdbaabecfee2a8bd13cd0f623867f468427

**Comment by robotfoot** [comment]
Awesome, thanks!

**Comment by marco44** [comment]
If you need a kettle job to migrate the data from this column, I'll need some help though (an export of the table… so I can work out how to extract this data as text).
