### ISSUE TITLE
Create postgres default value when SQL Server column not identity and has default value

### ISSUE THREAD

**Issue by Yenwod** [dalibo/sqlserver2pgsql#28]
Looks like default values set in SQL Server are not translating over to postgres, such as this:

[sign_in_count] [int] NOT NULL DEFAULT ((0))

In postgres, I'm getting this (missing the default):

sign_in_count          | integer                     | not null

I've got a ton of default values to migrate over.  I'd like to confirm that I'm not missing something obvious.   Thanks.  I'm using SQL Server 2005

**Comment by marco44** [comment]
Default values should be handled. If they are not for your table, it is a bug. Could you send me your full SQL Server export  at cousinmarc@gmail.com, and tell me what's missing, so I can solve the bug ?

Thanks a lot

**Comment by marco44** [comment]
I've looked a bit more into this. Until now, in the rare dumps that I had that had default values, those were generated with an alter column by SQL Server. Is this the case with your dump ? Or is the default value provided in the create table ?

**Comment by Yenwod** [comment]
Thank you, @marco44, for the fast response. I've sent the full dump file as requested.  As noted in the email, the default value is provided in create table.

**Comment by marco44** [comment]
675ecedd49e76bd508044ead9aa036034b664b0b should fix this. Please tell me.

**Comment by Yenwod** [comment]
@marco44, it works great.  Most default values are getting into the tables.  Thank you for such a quick fix.  What's interesting is that you are translating DEFAULT getdate() correctly as:

ALTER TABLE "public"."bulk_move_log" ALTER COLUMN "moved_when" SET DEFAULT CURRENT_TIMESTAMP;

but putting that correct translation into the unsure file. I'm wondering if it couldn't go into the after file?  

Thank you so much for a fantastic utility.  You've saved me a ton of time and I've learned a lot from studying your work.

**Comment by marco44** [comment]
As it is very simple, yes, it could go into the after file. The thing is, as soon as the script detects that the default value is a function, there are so many things that can go wrong that its simpler to just tell the user to double-check.

**Comment by Yenwod** [comment]
Good point.  Thank you again for fixing this issue so quickly.
