### ISSUE TITLE
Error while importing (This is a bug at ./sqlserver2pgsql.pl line 1897)

### ISSUE THREAD

**Issue by deepakbandela** [dalibo/sqlserver2pgsql#29]
Hello

I'm getting this error. Can you please let me know what is the issue and fix it as well?

Is there any way I can skip it?
```
$ ./sqlserver2pgsql.pl -conf conf_file -f /home/deepak/work/projects/nucleus/fract-data-unicode.sql 
WARNING: the source database is set as ARITHABORT OFF.
         It means that for SQL Server, 10/0 = NULL.
         You'll probably have problems porting that to PostgreSQL.
Line <INSERT [dbo].[RegistryUpload] ([pKey], [JobStartDate], [JobEndDate], [APINumber], [StateNumber], [CountyNumber], [OperatorName], [WellName], [Latitude], [Longitude], [Projection], [TVD], [TotalBaseWaterVolume], [TotalBaseNonWaterVolume], [StateName], [CountyName], [FFVersion], [FederalWell]) VALUES (N'cdc7d9cc-1bb9-4458-8060-fd8309f78185', CAST(N'2013-01-04 00:00:00.000' AS DateTime), CAST(N'2013-01-04 00:00:00.000' AS DateTime), N'04030470660000', N'04', N'030', N'Aera Energy LLC', N'King 78WBR-19', 35.4716124, -119.7453804, N'NAD83', 1801, 77742, NULL, N'California', N'Kern', 1, 0)
> (151) not understood. This is a bug at ./sqlserver2pgsql.pl line 1897, <$file> line 151.
```

**Comment by marco44** [comment]
Please send me your dump to cousinmarc at gmail com... I think i have never
seen an insert in a schema dump before :)
Le 27 janv. 2016 8:27 AM, "Deepak Bandela" <notifications@github.com> a
écrit :

**Comment by deepakbandela** [comment]
Its a huge 2.5GB file. I replaced it with just just the database schema file. now Im getting this

./sqlserver2pgsql.pl -conf conf_file -f /home/deepak/work/tools/sqlserver2pgsql/scripts/script.sql 
WARNING: the source database is set as ARITHABORT OFF.
         It means that for SQL Server, 10/0 = NULL.
         You'll probably have problems porting that to PostgreSQL.
You have to set up KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL=Y in /home/deepak/.kettle/kettle.properties.
If this file doesn't exist yet, start spoon from the kettle directory once. at ./sqlserver2pgsql.pl line 551.

**Comment by deepakbandela** [comment]
I ran spoon.sh in data-integration directory. It didnt create that ~/.kettle/kettle.properties file though.

I created it manually and set the value in the first line. 

It is the same error unfortunately :(

**Comment by marco44** [comment]
It should be very small. You must have your data exported in it, and it
should not be there... Please check your export options
Le 27 janv. 2016 8:50 AM, "Deepak Bandela" <notifications@github.com> a
écrit :

**Comment by deepakbandela** [comment]
Yes that's right I changed it and encountered another issue as mentioned above

**Comment by marco44** [comment]
Did spoon.sh start the gui?
Le 27 janv. 2016 8:52 AM, "Deepak Bandela" <notifications@github.com> a
écrit :

**Comment by deepakbandela** [comment]
yes it did.

**Comment by deepakbandela** [comment]
It created a kettle.properties file this time. I added the line KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL=Y in /home/deepak/.kettle/kettle.properties

and ran the command ./sqlserver2pgsql.pl -conf conf_file -f /home/deepak/work/tools/sqlserver2pgsql/scripts/script.sql 

But I didn't see any import happening.

deepak@deepak-Inspiron-5548:~/work/tools/sqlserver2pgsql$ ./sqlserver2pgsql.pl -conf conf_file -f /home/deepak/work/tools/sqlserver2pgsql/scripts/script.sql 
WARNING: the source database is set as ARITHABORT OFF.
         It means that for SQL Server, 10/0 = NULL.
         You'll probably have problems porting that to PostgreSQL.
deepak@deepak-Inspiron-5548:~/work/tools/sqlserver2pgsql$

**Comment by marco44** [comment]
Sure. sqlserver2pgsql only creates the sql scripts and the kettle job.

You have to run the sql scripts, then run kettle (through the kitchen
script), as explained in the doc.

**Comment by deepakbandela** [comment]
Thanks Marco. Got the DB migrated.
