### ISSUE TITLE
Error while import 

### ISSUE THREAD

**Issue by Bolik** [dalibo/sqlserver2pgsql#30]
Hi,
I've tried convert schema from MS SQL 2000
[schema.zip](https://github.com/dalibo/sqlserver2pgsql/files/114748/schema.zip)

perl ../sqlserver2pgsql/sqlserver2pgsql.pl -b before.sql -a after.sql -u unsure.sql -f s.sql
Line <if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[FK_ConcContractH_ConsContract]') and OBJECTPROPERTY(id, N'IsForeignKey') = 1)
> (1) not understood. This is a bug at ../sqlserver2pgsql/sqlserver2pgsql.pl line 1897, <$file> line 1.

**Comment by marco44** [comment]
I feel like there is something wrong with this dump. There are a lot of "drop something" in it. Is there an option you may have selected which asks for this in the dump ?

**Comment by Bolik** [comment]
You are right,
h'vi fixed it by disabling some export options
