### ISSUE TITLE
Importing Error line 1897

### ISSUE THREAD

**Issue by lainglo** [dalibo/sqlserver2pgsql#31]
Hi

I seem to be having a similar problem to issues #29 and #30, with the issue being raised on line 1897 and being tracked to line 81 of my SQL dump file.

[script.zip](https://github.com/dalibo/sqlserver2pgsql/files/208530/script.zip)

**Comment by lainglo** [comment]
I actually managed to fix this problem now by adding

`        # Ignore users and roles. Security models will probably be very different between the two databases
        elsif ($line =~ /^ALTER (ROLE|USER)/)
        {
            next;
        }`

at line 1843 (this seems to be a natural extension to the previous elseif clause). However now I get the same type of error but now occurring at line 84 of the SQL dump, which contains the code:

`/****** Object:  Schema [Old]    Script Date: 07/04/2016 11:53 ******/
CREATE SCHEMA [Old]
GO
/****** Object:  Schema [Presentation]    Script Date: 07/04/2016 11:53 ******/
CREATE SCHEMA [Presentation]
GO`

**Comment by marco44** [comment]
Hi, you are right about the correction.

The other problem is that it's the first time I get a dump with a CREATE SCHEMA without AUTHORIZATION

There are a lot of SQL Server proprietary things in this database. You'll probably have difficulty migrating it.

There are two things I won't correct: there is a create view with the object name at the following line. Just put the two lines as one manually (this part of the code is complex enough :( )

and EXEC [FFC_DW].sys.sp_addextendedproperty @name=N'Description'

I don't know what this FFC_DW comes to do here. So just remove this line. Anyway, the associated comment is "Default description - you should change this.", so you won't lose something important

I just committed a patch to correct the rest of the problems.

**Comment by lainglo** [comment]
thanks for the quick response!

The changes seem to have worked, but now I am running into an issue involving migration of a SPATIAL INDEX

```
This spatial index won't be migrated:
CREATE SPATIAL INDEX [SpatialIndex-20140310-133004] ON [dbo].[DimMunicipality]
(
        [Geometry]
)USING  GEOMETRY_GRID

... etc...
```

I have installed postGIS and it seems to be connected but I have probably overlooked something. I'll find some tests to run to see if it is correctly configured.

**Comment by marco44** [comment]
No. It's just that I don't have even the slightest idea of how to migrate this index. So the script just tells you that it's sorry but it ignores it.

If you know exactly what could be done with it, tell me. I think a PostgreSQL gist index on the geometry should do the trick, but I just haven't had to migrate geospatial data from SQL Server yet. And I'm not sure Kettle will do the trick. Maybe you'll have to use geokettle, I don't know.

But I sure am interested in your feedback to improve automation on this.

**Comment by marco44** [comment]
This won't be solved.
