### ISSUE TITLE
Error in generated kettle script.

### ISSUE THREAD

**Issue by JCallico** [dalibo/sqlserver2pgsql#35]
I'm not able to figure out why the generate kettle script always fails for this, and only this, table.

Here is the original table:

```
CREATE TABLE [dbo].[DEALER_PROFILE](
	[DealerCode] [varchar](20) NOT NULL,
	[DealerName] [varchar](30) NOT NULL,
	[RegionCode] [char](2) NOT NULL,
	[SalesDistrictCode] [char](2) NULL,
	[ServiceDistrictCode] [char](2) NULL,
	[Address1] [varchar](30) NULL,
	[Address2] [varchar](30) NULL,
	[Address3] [varchar](30) NULL,
	[City] [varchar](25) NULL,
	[Province] [char](3) NULL,
	[PostalCode] [char](7) NULL,
	[OperationsStartDate] [date] NULL,
	[TerminationDate] [date] NULL,
	[StatusCode] [char](1) NULL,
	[FacilityTypeCode] [char](1) NULL,
	[ShowroomCode] [bit] NULL CONSTRAINT [DF_DEALER_PROFILE_ShowroomCode]  DEFAULT ((0)),
	[LanguageCode] [char](2) NULL,
	[Phone] [char](10) NULL,
	[Fax] [char](10) NULL,
	[IsActive] [bit] NULL,
	[DealerPrefix] [varchar](20) NULL,
	[RegionDescription] [nvarchar](50) NULL,
	[ZoneCode] [char](2) NULL,
	[ZoneDescription] [nvarchar](50) NULL,
	[ModifiedBy] [varchar](50) NOT NULL CONSTRAINT [DF_DEALER_PROFILE_ModifiedBy]  DEFAULT (user_name()),
	[ModifiedDate] [datetime] NOT NULL CONSTRAINT [DF_DEALER_PROFILE_ModifiedDate]  DEFAULT (getdate()),
	[CreatedBy] [varchar](50) NOT NULL CONSTRAINT [DF_DEALER_PROFILE_CreatedBy]  DEFAULT (user_name()),
	[CreatedDate] [datetime] NOT NULL CONSTRAINT [DF_DEALER_PROFILE_CreatedDate]  DEFAULT (getdate()),
	[DealerSalesGroupId] [int] NULL,
	[DisplayDealerName] [varchar](100) NULL
 CONSTRAINT [PK_DEALER_PROFILE] PRIMARY KEY CLUSTERED 
(
	[DealerCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

```
This is the first error I get:

> 2016/07/11 13:26:32 - Table output.3 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Unexpected batch update error committing the database connection.

But if I copy and paste the generated sql directly on the Query window and run it, it works without any problem.

**Comment by marco44** [comment]
Usually the best place where to get the error is PostgreSQL's log... Could
you have a look?

**Comment by JCallico** [comment]
This is the error I see on PostgreSQL's logs: 

> EDT ERROR:  column "OperationsStartDate" is of type date but expression is of type character varying at character 574

**Comment by marco44** [comment]
OK so Java is trying to send a string when PostgreSQL is expecting a
date... that is really strange. do you know how to use kettle's GUI?
Le 11 juil. 2016 7:45 PM, "Javier Callico" <notifications@github.com> a
écrit :

**Comment by JCallico** [comment]
and here is the reduced SQL statement:

`INSERT INTO "Mazda"."DEALER_PROFILE" ("DealerCode", "OperationsStartDate", "CreatedDate") VALUES ( '11142',  '1987-03-24',  '2013-10-25 17:10:55.620000 -04:00:00') `

It seems to complain about the column of type "date" but accepts the value of the column of type "datetime".

Note that this only happens from kettle using the parameterized query.

**Comment by JCallico** [comment]
Spoon? Yes, I have it open it.

**Comment by marco44** [comment]
Great. Can you find in which node kettle starts to think that this field is
varchar ?
Le 11 juil. 2016 7:53 PM, "Javier Callico" <notifications@github.com> a
écrit :

**Comment by JCallico** [comment]
I just checked and there are only two tables with columns of type [date] and these are the only two failing so the problem is definitely associated to this data type.

**Comment by marco44** [comment]
I'm not sure I have seen a date field until today... datetime a lot though.

It looks like this doesn't it ?
http://forums.pentaho.com/showthread.php?128538-Date-vs-DateTime

**Comment by marco44** [comment]
I'm almost sure it comes from this. Can you try replacing this function's prototype like this and regenerate kettle's files… I know I would need this function someday :)

```
sub sql_convert_column
{
    my ($colname,$coltype)=@_;
    my %functions = ( 'uuid' => 'lower');
    if (defined ($functions{$coltype}))
    {
        return $functions{$coltype} . '([' . $colname . '])';
    }
    elsif ($coltype eq 'date')
    {
    	return 'CONVERT(DATETIME,[' . $colname . '])';
    }
    else
    {
        return "[$colname]";
    }
}
```

**Comment by JCallico** [comment]
I was fidgeting with the same function myself before creating the GitHub issue.

This is the error I got after applying your change:

> Caused by: java.sql.SQLException: The conversion of a date data type to a datetime data type resulted in an out-of-range value.

It seems to be associated with another data column having the following value '0001-01-01' which seems to be value for [date] but invalid for [datetime]

`SELECT CONVERT(DATETIME, '0001-01-01')`

**Comment by JCallico** [comment]
By the way, if I delete the row with the invalid value the transformation works so we are in the right path.

**Comment by marco44** [comment]
The date datatype can hold dates from Jan 1 of year 1 thru Dec 31, 9999.  The datetime datatype can only hold dates from Jan 1, 1753 thru Dec 31, 9999

I always feel I'm going crazy when working with SQL Server :)

We have another possibility, but it is a bit ugly: instead of doing this, we could add a cast from varchar to date in PostgreSQL and remove it at the end (see the example of the UUID type)

**Comment by JCallico** [comment]
I switched to DATETIME2 and now the select is valid but get the same error from Java.

**Comment by marco44** [comment]
No, datetime2 won't work either. Have a look at what is done for uuid (adding transparent casts in postgresql, so that postgres does the conversion itself)

**Comment by JCallico** [comment]
Ok, let me try doing something similar to what is currently done for uuid.

**Comment by JCallico** [comment]
I'm sending you a pull request, please review.

**Comment by JCallico** [comment]
Sorry I have to open this issue again because now the incremental script is failing.

This is the error I'm getting when running the kettle script:
The data type of field #12 is not the same as the first row received: you're mixing rows with different layout. Field [OperationsStartDate Date] does not have the same data type as field [OperationsStartDate String(30)].

**Comment by JCallico** [comment]
[Update] I opened the incremental kettle script on spoon and changed the current statement been used on the "Table Input" step from:

`SELECT * FROM "dbo"."DEALER_PROFILE"`

to:

`SELECT ...., to_char("OperationsStartDate", 'YYYY-MM-DD') AS "OperationsStartDate", ... FROM "dbo"."DEALER_PROFILE"`

and it worked fine. 

I guess we need to modify the generation process to include the detailed field list with the necessary castings on PgSQL as we are currently doing with MSSQL.

**Comment by JCallico** [comment]
See pull request #37 which contains a fix for the issue described above.

**Comment by marco44** [comment]
Thanks a lot
