### ISSUE TITLE
Xml Schema Collections cause the script to abort

### ISSUE THREAD

**Issue by JCallico** [dalibo/sqlserver2pgsql#38]
Given the following table definition:

```
CREATE TABLE [sample].[EventQueue](
	[EventId] [int] IDENTITY(1,1) NOT NULL,
	[Data] [xml](CONTENT [sample].[Event]) NULL
 CONSTRAINT [PK_EventQueue] PRIMARY KEY CLUSTERED 
 (
	[EventId] ASC
 ) ON [PRIMARY]
) 
```

The script aborts with the following error:

> Cannot parse colqual <(CONTENT [sample].[Event])>

I'll try to come up with a solution but any suggestion will be greatly appreciated.

**Comment by marco44** [comment]
Just ignore what's in parenthesis? What is it exactly ?
Le 13 juil. 2016 5:14 PM, "Javier Callico" <notifications@github.com> a
écrit :

**Comment by JCallico** [comment]
That's exactly what I did. I have a patch ready but I'm bundling with other changes.

**Comment by JCallico** [comment]
See #43
