### ISSUE TITLE
PRIMARY XML INDEX cause the script to abort

### ISSUE THREAD

**Issue by JCallico** [dalibo/sqlserver2pgsql#41]
The following definition causes the script to abort:

```
CREATE PRIMARY XML INDEX [IX_Table1_Data_Primary] ON [public].[Table1]
(
    [Data]
)
```

I'd love to hear what should be done about it. Ignore it?

**Comment by marco44** [comment]
I think so: there is no index on XML in PostgreSQL…

**Comment by marco44** [comment]
Hi. I didn't check, but it this one to close too ? It must have been in one of the pull request :)

**Comment by JCallico** [comment]
I just checked with my test data. The problem is still there.

**Comment by marco44** [comment]
Could you send me a (complete) dump with this at cousinmarc at gmail ?
(I'll keep it private of course)

**Comment by marco44** [comment]
Hi, any news on this ?
