### ISSUE TITLE
Incorrect conversion for datetimeoffset

### ISSUE THREAD

**Issue by JCallico** [dalibo/sqlserver2pgsql#42]
The following table definition:

```
CREATE TABLE [public].[Table1](
	[EventId] [int] IDENTITY(1,1) NOT NULL,
	[CreateDate] [datetimeoffset](7) NOT NULL,
)
```
generates the following PostgreSQL code:

```
CREATE TABLE "public"."Table1"( 
	"EventId" int NOT NULL,
	"CreateDate" timestamp with time zone(7) NOT NULL);
```

The code above is not valid. If I remove "(7)" then the script works.

Is this the correct thing to do?

**Comment by marco44** [comment]
That should be good, yes. Anyway, timestamp's max precision is 6 in PostgreSQL. And I think that kettle only keeps the first three digits (it's a limitation of kettle: http://forums.pentaho.com/showthread.php?93206-Timestamp-loosing-precision , I don't think it has been corrected)

**Comment by JCallico** [comment]
ahhhh that's why the Kettle script is failing for timestamp types.

I'm going to try to convert to varchar as it was done to uuid and date.

**Comment by marco44** [comment]
Yes. That's a shame that kettle doesn't do this correctly, but it is
probably the right way to do it :(

**Comment by JCallico** [comment]
I already have this issue resolved on my fork, these are the functions I used:

For selecting from SQL:

`convert(varchar(50), {colname}, 121)`

For selecting from PostgreSQL (on the incremental script):

`to_char({colname} AT TIME ZONE 'UTC', 'YYYY-MM-DD HH:MI:SS.US+00')`

There was no need to add a global CAST.

I've tested this change on both, migration and incremental, scripts.

**Comment by marco44** [comment]
That's perfect… printing it at UTC was the correct way to do it.
