### ISSUE TITLE
Kettle script fails for XML columns

### ISSUE THREAD

**Issue by JCallico** [dalibo/sqlserver2pgsql#44]
The kettle script is failing for XML columns with the following error:

```
2016-07-14 13:56:07 EDT ERROR:  column "Xml" is of type xml but expression is of type character varying at character 220
2016-07-14 13:56:07 EDT HINT:  You will need to rewrite or cast the expression.
```

Since this error was similar to the ones experienced with uuid and date I decided to do a custom casting for XML as well. I changed the script to select XML columns from SQL Server like this:

`convert(varchar(max), [Xml]) AS "Xml"`

Didn't work. I then added a cast for the XML type as we are doing with the other types. This time I got the following error:

```
2016-07-14 14:21:56 EDT ERROR:  cannot drop cast from character varying to xml because it is required by the database system
2016-07-14 14:21:56 EDT STATEMENT:  DROP CAST IF EXISTS (varchar as xml)
```
Any ideas about how to address this issue?

**Comment by marco44** [comment]
The problem is that the varchar -> xml cast exists, but isn't 'as assignment' or 'implicit' (it is explicit). So we cannot create the cast.

The only (ugly) solution I see is messing with the system catalog:

Instead of the CREATE CAST:
update pg_cast set castcontext='i' where castsource='character varying'::regtype and casttarget='xml'::regtype;

Instead of the DROP CAST:
 update pg_cast set castcontext='e' where castsource='character varying'::regtype and casttarget='xml'::regtype;

It's not that big a problem, as we cleanup the mess at the end (it's not worse than creating new casts anyway).

What do you think ?

**Comment by JCallico** [comment]
@marco44, my knowledge of PostgreSQL internals is not that advanced so I have to rely on you.

I tried your solution, with and without casting the XML column on the select statement and it didn't work.

One option is to produce a custom INSERT statement like the one recommended [here](http://stackoverflow.com/questions/12050945/how-can-i-insert-an-xml-document-in-postgresql-in-java), basically wrapping the XML column into an XML function on the INSERT statement:

`INSERT INTO xml_docs(id, gkuzu) VALUES (1, XML('<foo>Hello World!</foo>'));`

How difficult will that be?

**Comment by marco44** [comment]
It's feasible with a SQL job in kettle. But il will be very slow (it will recompile the statement each time).

My solution should work: it works when preparing the statement manually… and it's the one we use with create cast, we just do the operation directly in PostgreSQL's catalogs.

If you want to be sure it has worked, try this (adapting to your schema, of course), before and after updating the system catalog:
`prepare xxx (varchar) as insert into myxmltable (myxmlcolumn) values ($1))`


Can you detail what you tried ? Here is what should happen:

First run (and commit if you aren't in autocommit):
`update pg_cast set castcontext='i' where castsource='character varying'::regtype and casttarget='xml'::regtype;`

Then try the kettle job, without any cast… you shouldn't get the message asking you to cast.

**Comment by JCallico** [comment]
you are right... i ran it again and it seems to be working... let me try again.
