### ISSUE TITLE
Be a little bit more clear about usage

### ISSUE THREAD

**Issue by MichaelHouze** [dalibo/sqlserver2pgsql#49]
It's far from obvious that

`sqlserver2pgsql.pl -f my_sqlserver_script.txt -b name_of_before_script -a name_of_after_script -u name_of_unsure_script`

> The before script contains what is needed to import data (types, tables and columns). The after script contains the rest (indexes, constraints). It should be run after data is imported. The unsure script contains objects where we attempt to migrate, but cannot guarantee, such as views.

will in fact generate before, after and unsure sql scripts, I first thought I have to provide them !

**Comment by marco44** [comment]
Hi,

I'm not a native English speaker. If you have an idea of how to rephrase this, please do :)

**Comment by MichaelHouze** [comment]
Here is an alternative:

`sqlserver2pgsql.pl -f input_sql_dump -b output_before_script -a output_after_script -u output_unsure_script`

sqlserver2pgsql Perl script process your SQL raw dump "input_sql_dump" and produce these three scripts:

- output_before_script: contains what is needed to import data (types, tables and columns)

- output_after_script: contains the rest (indexes, constraints)

- output_unsure_script: contains objects where we attempt to migrate, but cannot guarantee, such as views

--
You may also provide default value which will be displayed after the conversion process, so

`sqlserver2pgsql.pl -f my_sqlserver_script.txt `

will output:

```
my_sqlserver_script.txt processed
before script "output_before_script"  contains x tables, y foo, z bar
output_after_script contains x indexes...
output_unsure_script contains y procedures, ...
```

default in such case would be input_script_name-(before|after|unsure).extension
or input_script_name.(before|after|unsure)   (extension changed)

Hope this help.

**Comment by marco44** [comment]
Thanks, applied
