### ISSUE TITLE
I migrate AspNetCore.Identity tables to postgres but all tables were migrated lowercase

### ISSUE THREAD

**Issue by senzacionale** [dalibo/sqlserver2pgsql#50]
For example:

`AspNetUsers`is original table name

after migrations is name `aspnetusers`. Same is with table fields

How can I migrate it with original upper case

**Comment by marco44** [comment]
Hi,

sqlserver2pgsql doesn't do it. It's an extremely bad idea, you'll need to double quote all objets name in all your queries if you create objects names like that in PostgreSQL.

If you create your objects with lower case names, you can still use CamelCase in your queries: lower case names are «case insensitive» in PostgreSQL: as long as you don't use double quotes around object names, they are all lower cased when the parser searchs them in the database catalog.

If you really, absolutely need it, it shouldn't be very hard to add to sqlserver2pgsql. Patches are welcome :)

**Comment by marco44** [comment]
Wow, I just realized, there is already an option for this… -keep_identifier_case.

Sorry about that, I feel really dumb :)
