### ISSUE TITLE
Help sqlserver2pgsql.pl 

### ISSUE THREAD

**Issue by paulpoterasiH** [dalibo/sqlserver2pgsql#51]
Hello,

I have a new project that will migrate a SQL Server database into PostgreSQL. I found this tool, but i don't know how to use it.

For example, I installed perl like is written here https://learn.perl.org/installing/windows.html, I created a dumb sql file for my schema and i put it into a folder migrateDatabase.

In that folder I copied sqlserver2pgsql.pl file.

From my command prompt I executed this command line :

`C:\migrateDatabase>perl sqlserver2pgsql.pl -f input_sql_dump.sql -b output_before_script -a output_after_script -u output_unsure_script`

I recieve this error:

> Bareword found where operator expected at C:\migrateDatabase\sqlserver2pgsql.pl line 342, near "s/{colname}/[$colname]/gr"
> Bareword found where operator expected at C:\migrateDatabase\sqlserver2pgsql.pl line 364, near "s/{colname}/"$colname"/r"
> syntax error at C:\migrateDatabase\sqlserver2pgsql.pl line 342, near "s/{colname}/[$colname]/gr"
> syntax error at C:\migrateDatabase\sqlserver2pgsql.pl line 364, near "s/{colname}/"$colname"/r"
> BEGIN not safe after errors--compilation aborted at C:\migrateDatabase\sqlserver2pgsql.pl line 4111.

What i do wrong? 

Can you help me? 

Maybe it will be great if you can create a video tutorial for this tool.

Thanks a lot!

**Comment by marco44** [comment]
Can you paste the result of "perl -version" ?

**Comment by paulpoterasiH** [comment]
`This is perl 5, version 12, subversion 3 (v5.12.3) built for MSWin32-x86-multi-thread

Copyright 1987-2010, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.`

**Comment by marco44** [comment]
Ok. This is very old. As the procedure you pasted… The latest is 5.24. The one you are using is 6 years old. It should work though, but you'd better install strawberry perl from scratch without padre and the like: http://strawberryperl.com/

If you don't want to mess with your system, just use the portable version from this pag :http://strawberryperl.com/releases.html

**Comment by paulpoterasiH** [comment]
Thanks a lot for your fast response. 

I will try to do that. I tried to figure what i do wrong for 5 hours. :(

**Comment by marco44** [comment]
The code I wrote should have worked with Perl 5.12, but I don't have one that old at hand, so anyway it's faster to make you update to something recent for a start. Please remove padre and its Perl. This tutorial page must be very old :)

**Comment by paulpoterasiH** [comment]
@marco44  Thanks a lot for your response. I did what you told me.

Now, when I run the command line : 

`C:\migrateDatabase>sqlserver2pgsql.pl -f input_sql_dump.sql -b output_before_script -a output_after_script -u output_unsure_script`

I recieve this:

> Expects a SQL Server SQL structure dump as -f (preferably unicode)
-conf uses a conf file. All options below can also be set there. Command line options will overwrite conf options
-i tells C:\migrateDatabase\sqlserver2pgsql.pl to create a case-insensitive PostgreSQL schema
-nr tells C:\migrateDatabase\sqlserver2pgsql.pl not to convert the dbo schema to public. dbo will stay dbo
-num tells C:\migrateDatabase\sqlserver2pgsql.pl to convert numeric xxx,0 to int, bigint, etc. Will not keep numeric scale and precision for the converted
-relabel_schemas gives a list of schemas to rename. For instance -relabel_schemas 'source1=>dest1;source2=>dest2'
  -nr simply cancels the default dbo=>public remapping. Don't forget to put the remapping between quotes
-keep_identifier_case tells C:\migrateDatabase\sqlserver2pgsql.pl to keep the case of sql server database objects (not advised). Default is to lowercase everything.
before_file contains the structure
after_file contains index, constraints
validate_constraint validates the constraints that have been created
sort_size will change size of sort batch for the incremental job. Too small and it will be slow, too big and you will get Java Out of Heap Memory errors.
sort_size is 10000, which is very low, to try to avoid problems. First, raise java heap memory (in the kitchen script), then try higher values if you need more speed
use_pk_if_possible is false (0) by default. You can put it to 1 (true), or give a comma separated list of tables (with schema). Compared case insensitively
unsure_file contains things we cannot guarantee will work, such as views

If you are generating for kettle, you'll need to provide connection information
for connecting to both databases:
-sd: sqlserver database
-sh: sqlserver host
-si: sqlserver host instance
-sp: sqlserver port
-su: sqlserver username
-sw: sqlserver password
-pd: postgresql database
-ph: postgresql host
-pp: postgresql port
-pu: postgresql username
-pw: postgresql password

Where should I put the config file and what name it must have?

**Comment by marco44** [comment]
You don't need a config file. You only need one if you don't want to specify all the options everytime. That's really weird: the message you get is only displayed when there is an error on the command line. And yours is correct.

**Comment by paulpoterasiH** [comment]
Let me ask you something:

I wrote this command line: 

`C:\migrateDatabase>sqlserver2pgsql.pl -f input_sql_dump.sql -b output_before_script -a output_after_script -u output_unsure_script`

After that he ask me to open the file **sqlserver2pgsql.pl**. I say open and the immediately output in the command prompt is this
`C:\migrateDatabase>sqlserver2pgsql.pl -f input_sql_dump.sql -b output_before_script -a output_after_script -u output_unsure_script
C:\migrateDatabase\sqlserver2pgsql.pl [-k kettle_output_directory] -b before_file -a after_file -u unsure_file -f sql_server_schema_file[-h] [-i]

Expects a SQL Server SQL structure dump as -f (preferably unicode)
-conf uses a conf file. All options below can also be set there. Command line options will overwrite conf options
-i tells C:\migrateDatabase\sqlserver2pgsql.pl to create a case-insensitive PostgreSQL schema
-nr tells C:\migrateDatabase\sqlserver2pgsql.pl not to convert the dbo schema to public. dbo will stay dbo
-num tells C:\migrateDatabase\sqlserver2pgsql.pl to convert numeric xxx,0 to int, bigint, etc. Will not keep numeric scale and precision for the converted
-relabel_schemas gives a list of schemas to rename. For instance -relabel_schemas 'source1=>dest1;source2=>dest2'
  -nr simply cancels the default dbo=>public remapping. Don't forget to put the remapping between quotes
-keep_identifier_case tells C:\migrateDatabase\sqlserver2pgsql.pl to keep the case of sql server database objects (not advised). Default is to lowercase everything.
before_file contains the structure
after_file contains index, constraints
validate_constraint validates the constraints that have been created
sort_size will change size of sort batch for the incremental job. Too small and it will be slow, too big and you will get Java Out of Heap Memory errors.
sort_size is 10000, which is very low, to try to avoid problems. First, raise java heap memory (in the kitchen script), then try higher values if you need more speed
use_pk_if_possible is false (0) by default. You can put it to 1 (true), or give a comma separated list of tables (with schema). Compared case insensitively
unsure_file contains things we cannot guarantee will work, such as views
If you are generating for kettle, you'll need to provide connection information
for connecting to both databases:
-sd: sqlserver database
-sh: sqlserver host
-si: sqlserver host instance
-sp: sqlserver port
-su: sqlserver username
-sw: sqlserver password
-pd: postgresql database
-ph: postgresql host
-pp: postgresql port
-pu: postgresql username
-pw: postgresql password`

Should I modify the sqlserver2pgsql.pl file? Because I see that it writes something about the kettle_output_directory.

I hope that i don't disturb you with all my questions. But I don't know who to ask.

**Comment by paulpoterasiH** [comment]
It works!!!!!!!!!

I have experience only with .NET applications, so this is a real challenge to me. I hope that i will succeed to migrate the entire database to PostgreSQL. 

You saved my day!

If you will come in Romania, I want to drink some beers with you ! 

Thank you very much!

**Comment by marco44** [comment]
No problem. The 'kettle dir' you were wondering about will be needed only if you need to migrate data too.

**Comment by marco44** [comment]
If I ever come to Romania, I'll do my best to have a drink with you :)

**Comment by paulpoterasiH** [comment]
Yes, this is the next step for me.

I will try to read the documentation and i hope that i will succeed to migrate my data.

You really helped me alot today. I was stuck with that version of Perl.

Have a nice day/night!

Thank you very much!

**Comment by srg301091** [comment]
@paulpoterasiH how did you get it worked?

**Comment by paulp88** [comment]
I use my personal account here, the other one is from my work.

I had to install the right version of Perl, 5.24, and after that to run the command like @marco44  said:

`perl sqlserver2pgsql.pl -f input_sql_dump.sql -b output_before_script -a output_after_script -u output_unsure_script`

That was all!

I will try this weekend to see the kettle tool to migrate the database.

**Comment by paulpoterasiH** [comment]
I created a new folder called tmp in my folder. Inside that folder I have 3 folders before, after and unsure.

In my config file I set :
`# Source SQL Server Dump. Obviously compulsory
sql server dump filename=/tmp/dump
# These are used to generate SQL scripts (this is the only thing that is always done)
before file=D:\migrateDatabase\tmp\before
after file=D:\migrateDatabase\tmp\after
unsure file=D:\migrateDatabase\tmp\unsure`

When I run this command
`D:\migrateDatabase>perl sqlserver2pgsql.pl -conf example_conf_file -f input_sql_dump.sql` 

I receive this error: 
> Cannot open D:\migrateDatabase\tmp\before, Permission denied at sqlserver2pgsql.pl line 2023.

What should I do?

**Comment by marco44** [comment]
It seems you don't have the permission to write in this directory (tmp) ? Did you create it with the same user as you use to run sqlserver2pgsql ?

**Comment by paulpoterasiH** [comment]
Hello @marco44 !

Yes. I did that and I gave full control to that directory (tmp).

**Comment by marco44** [comment]
Try replacing \ with / (perl uses / as directory separators, as unix does)

**Comment by paulpoterasiH** [comment]
Thank you for your reply.

It was my fault. I configure my config file in a wrong way.

This is the correct form to do that:

` Source SQL Server Dump. Obviously compulsory
sql server dump filename=D:\migrateDatabase\tmp\dump

These are used to generate SQL scripts (this is the only thing that is always done)
before file=D:\migrateDatabase\tmp\before\before_script
after file=D:\migrateDatabase\tmp\after\after_script
unsure file=D:\migrateDatabase\tmp\unsure\unsure_script`

Sorry for losing your time. It works. I have now in my kettle folder the .ktr files.

I believe that this files  should open in the kettle tool. Is this right? 

Thank you again for your time!

**Comment by marco44** [comment]
Yes, you'll need to use kettle. That is explained at the end of the README

**Comment by paulpoterasiH** [comment]
Thank you for all @marco44 !

**Comment by paulpoterasiH** [comment]
@marco44 I succeeded to migrate my data from Microsoft SQL to PostgreSQL.

I have one little problem. When I use your tool, it converts my column of type GUID ( uniqueidentifier) into uuid. This is the correct way.

But when i open my kettle file I see that my GUID Column is transformed in the output table into character varying(40).

Is there any chance to change this behavior?

**Comment by marco44** [comment]
It's on purpose: the GUID type is not supported by kettle (because of the Java driver). So I just convert it to a varchar as a temporary type… it was easier than patching Kettle :)

**Comment by paulpoterasiH** [comment]
Ok @marco44 .

Thank you very much!

**Comment by srg301091** [comment]
@marco44 can this tool migrate functions?

**Comment by marco44** [comment]
No. PostgreSQL's PL languages are very different from Transact-SQL.

**Comment by marco44** [comment]
(last question added to the FAQ)

**Comment by thoangtd** [comment]
Hi all,
I had problem when convert data with error 
Line <CREATE SEQUENCE [dbo].[dotcm_approval_history_seq]
> (91) not understood. This is a bug at sqlserver2pgsql.pl line 2026, <$file> line 91.
--- in line 91 
CREATE SEQUENCE [dbo].[dotcm_approval_history_seq] 
Pls help me !

**Comment by marco44** [comment]
Please send me the dump (cousinmarc at gmail dot com), so I can find out what's wrong with it.

Regards

**Comment by thoangtd** [comment]
i had sent a email for cousinmarc @gmail.com pls check your box
Thanks and Best regards

**Comment by marco44** [comment]
For anyone coming after this, please open another thread if you have an issue. We will continue here for this one, but it will make it easier for me if I have a different issue each time.

It's the first dump ever I get with 'CREATE SEQUENCE'. I'll try to provide a patch ASAP.

**Comment by marco44** [comment]
This should be solved by commit 5eb4e00135e6326513455a275eb0df6e2867a8b1.

Please tell me.
