### ISSUE TITLE
Handle SPARSE columns

### ISSUE THREAD

**Issue by McDoit** [dalibo/sqlserver2pgsql#54]
First, thank you for a really nice script and effort on this!

I have ran into a problem with the script and SPARSE columns
https://msdn.microsoft.com/en-us/library/cc280604.aspx
Which i use in some tables

`Cannot understand       [DecimalValue] [decimal](18, 2) SPARSE  NULL`

It was easily solved by removing SPARSE from the column declaration in the base sql file

But i reported it just in case :)

**Comment by marco44** [comment]
Thanks a lot. Could you provide me the dump file (privately), so I patch this and add it to regression testing ?

Regards

**Comment by McDoit** [comment]
Thanks for the quick reply

The dump i have is quite big, but i think it should be enough to add a column to any table on the form
`[DecimalValue] [decimal](18, 2) SPARSE NULL,`

**Comment by marco44** [comment]
This problem should be solved. Please confirm.

**Comment by marco44** [comment]
Forgot to mention:

I think it is fixed by b93f9909099a01a11a48f2df58f12d80f6594551

**Comment by McDoit** [comment]
Thank you, it solved the issue!
