### ISSUE TITLE
Kettle filename takes both paths

### ISSUE THREAD

**Issue by McDoit** [dalibo/sqlserver2pgsql#56]
Hello again!

Went into the part of the kettlefiles now for a test run of transfers as well, and ran into this while running on windows:

`<filename>D:\postgres\D:\kettlefiles\publicweb-Sections.ktr</filename>`

It should omit the `D:\postgres\` part of that path, but cant really understand how to solve it.

I did run `sqlserver2pgsql.pl` in my `D:\postgres` folder, and had set the -k parameter to `-k "D:\kettlefiles"`

It might work if i do `-k "..\kettlefiles"`

Or can the migration.kjb find the files even if they are relative to it?

**Comment by McDoit** [comment]
`-k "..\kettlefiles"` works but not relative files, then they need to be in the Spoon folder

**Comment by marco44** [comment]
That's a bit weird, I recall doing this once in windows (but a few years ago).

Can you give it a try with "/" instead of "\" as a separator ?

**Comment by marco44** [comment]
While re-reading this, I think I don't fully understand your problem.

Did it add D:\postgres ahead of your path (your current directory) ? Please confirm, I'll give it a look.

**Comment by McDoit** [comment]
Yeah it added D:/postgres before the filepath to the <filename> element in the migration.kjb

Was
<filename>D:\postgres\D:\kettlefiles\publicweb-Sections.ktr</filename>
Should be
<filename>D:\kettlefiles\publicweb-Sections.ktr</filename>

when i specified to put the kettlefiles in another folder with -k "D:\kettlefiles"

It added the files correctly to the right folder, but the then the wrong path in the  migration.kjb

**Comment by marco44** [comment]
I just have this issue opened now. Did you find a way to solve this ?

**Comment by McDoit** [comment]
Hello, sorry for a late reply.

No didn't try to fix it myself, i have zero knowledge about PERL so don't even know where to start.

As it is now after i run the script, i have to go into the migration.kjb file and find-replace all instances of `D:\postgres\` with an empty value

**Comment by marco44** [comment]
Took me a while, as I'm not quite at home in windows. Please tell me if the latest commits correct this

**Comment by McDoit** [comment]
And sorry, forgot to close this one, but yes it is working now, thank you! :)
