### ISSUE TITLE
Correctly transform filtered indexes

### ISSUE THREAD

**Issue by McDoit** [dalibo/sqlserver2pgsql#57]
I have a couple of filtered indexes in my MSSQL which the script don't translate correctly
For example:
```
CREATE UNIQUE NONCLUSTERED INDEX [UC_OnePartBase] ON [obj].[Parts]
(
	[ObjectId] ASC
)
WHERE ([ParentId] IS NULL)
```
Translate into
`CREATE UNIQUE INDEX "UC_OnePartBase" ON "obj"."Parts" ("ObjectId" ASC);`

But should be 
`CREATE UNIQUE INDEX "UC_OnePartBase" ON "obj"."Parts" ("ObjectId" ASC) WHERE ("ParentId" is null);`

Following
https://www.postgresql.org/docs/current/static/indexes-partial.html
And
http://stackoverflow.com/a/16236566/5863847

If this isn't possible, can they be moved the "unsure" file instead of the "post"?

**Comment by marco44** [comment]
Yes, you're right. 

Please test 97c1e0b44bf4ce6cba9b22dfc088980386716e3a

**Comment by marco44** [comment]
the patch does both: try to convert the sql, and put it in unsure anyway, as there could be fancy sql constructs in the where clause.

**Comment by McDoit** [comment]
Really nice, thank you!

But to you think you can perform the replace of '[' and ']' of it at least?

And on a sidenote, a check containg with `CHECK (([ParentId]<>[Id]))` becomes `CHECK (ParentId]<>[Id)` in the unsure file.
Either dont touch them as well or replace with double quote as well?

**Comment by marco44** [comment]
b87c863a0b182ba6de190f2874bdb68e92e8cf23 should solve the where problem. It's still very basic, as there are usually very few of those indexes, and I don't want to write something to parse the where syntax, it would be quite complex for a very small reward.

I can't reproduce your problem with the check constraint. Could you give me the whole table definition ?

**Comment by McDoit** [comment]
Will check the where problem soon, but here is the check constraint data

MS SQL Constraint:
```
ALTER TABLE [core].[Places]  WITH CHECK ADD  CONSTRAINT [core_Places_SelfParent] CHECK  (([ParentId]<>[Id]))
GO
```
Postgres:
`ALTER TABLE "core"."Places" ADD CONSTRAINT "core_Places_SelfParent" CHECK (ParentId]<>[Id);`

MS SQL Table
```
/****** Object:  Table [core].[Places]    Script Date: 2017-02-21 09:50:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [core].[Places](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
	[TypeId] [tinyint] NOT NULL,
	[ParentId] [bigint] NULL,
	[Coordinates] [geography] NULL,
 CONSTRAINT [PK_Place] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UC_Places_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC,
	[TypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
```

Postgre Table
```
CREATE TABLE "core"."Places"( 
	"Id" bigint NOT NULL,
	"Name" citext NOT NULL,
	"TypeId" smallint NOT NULL,
	"ParentId" bigint,
	"Coordinates" geography);
```

**Comment by marco44** [comment]
e38cdb02f925d17a7e26fde5eae98e7f6ebddee0 should improve your check constraints.

Do you migrate data too ? I'm interested in knowing how it goes with geometry/geography (I don't know if anyone has used this part of the code yet, that's the problem with free software :) )

**Comment by McDoit** [comment]
I tried to migrate data, but im running postgres on Amazon RDS so have issues running the kettle scripts for it

Error:
`2017/02/22 16:37:31 - SQL SCRIPT START - Couldn't execute SQL: UPDATE pg_cast SET castcontext='i' WHERE castsource='character varying'::regtype AND casttarget='xml'::regtype`

Already migrated the data using Amazon DMS but that gave me other issues. so will look into get this working with kettle on a local postgresserver, or running pgloader

**Comment by marco44** [comment]
Can you try running this SQL statement manually ? I suspect it's amazon preventing you from running it…

**Comment by McDoit** [comment]
Yes it is, so I don't have so much luck with Kettle sadly.

But your pre, post and unsure scripts have helped a lot with what i have!

**Comment by marco44** [comment]
I just thought there might be another way, using intermediary views to solve the jdbc cast problem. If you are interested, I could give it a try tomorrow (it's getting late in France :) )

**Comment by McDoit** [comment]
I didn't really understand what that line of SQL was supposed to do, but searching for it i found out that you are not supposed to update the systems catalogs directly, but i assumed it was done for a reason :P  

According to http://stackoverflow.com/a/21756113/5863847

But yes, if you think it can be solved in any way it would be really nice of you!

**Comment by marco44** [comment]
The problem is that kettle is a java application, using prepared statements, and it prepares statements using the types it has internally for data. For instance, it sees xml as text (varchar), so the jdbc drivers prepares its query telling postgres that column x contains text. PostgreSQL rejects the statement telling that it wants xml, not text.

The update to the system catalog was done to tell postgres that it is allowed to cast varchar to xml without raising errors. So I have to find a workaround. But my idea of working around the problem with a view doesn't work,

**Comment by marco44** [comment]
I have another solution I just thought of, which is so obvious that I feel a bit stupid… you could alter these columns types just for the duration of the kettle job… it would slow down the process though, as it means a full table rewrite at the end.

Just find the few types where kettle tries to do these updates to system catalogs, and alter their types in the database.

At the end, just convert them back to the real type: 

"alter table test alter b type xml using b::xml;"

You'll also have to ask kettle not to do those updates to the system catalog. This is the easy part, just run the spoon GUI and empty these two steps in the migration.kjb file (I think they are the first and the last ones).

**Comment by McDoit** [comment]
I'm trying out that idea now, sounds like a really good way to solve it, and i should be able to take my time to alter the columns afterwards

But now i'm running into issues with Spoon and the driver (had similar before with commandline)

`Driver class 'net.sourceforge.jtds.jdbc.Driver' could not be found, make sure the 'MS SQL Server' driver (jar file) is installed.`

When i'm setting up a database connection in Spoon GUI it works, taking the native driver etc, but the .ktr files with the actual jobs fail with the above error.
But the .ktr files are specified with <access>Native</access> so i dont get it why it's trying to use the jtds driver?

**Comment by McDoit** [comment]
On a related note to this actual ticket
https://github.com/dalibo/sqlserver2pgsql/commit/e38cdb02f925d17a7e26fde5eae98e7f6ebddee0
does improve the check handling, but it removes the [ and ] in the where clasue and doesnt replace them with a " instead.

**Comment by marco44** [comment]
You have the access attribute to Native, in what sqlserver2pgsql generates, don't you ? But type is MSSQL ?

I didn't notice, but the freetds driver was removed from kettle 7 : http://jira.pentaho.com/browse/BISERVER-11835

Not really funny…

Please try this (I'll patch sqlserver2pgsql if this works):

* https://msdn.microsoft.com/library/mt484311.aspx (download and install the driver in the lib directory). This is explained here: http://wiki.pentaho.com/display/EAI/MS+SQL+Server
* replace MSSQL with MSSQLNATIVE in all occurences in sqlserver2pgsql, and re-run sqlserver2pgsql

Please tell me how it goes.

**Comment by marco44** [comment]
About the [] removal, most users will ask sqlserver2pgsql to not keep the case of identifiers (most client code won't work if they keep the case), so adding "" will do more harm than not putting them.

**Comment by McDoit** [comment]
Works better as in that it gives a better error:

` The property integratedSecurity does not contain a valid boolean value. Only true or false can be used.`

Trying to figure out if i can add it in the 'attributes' area like 
`<attribute><code>EXTRA_OPTION_MSSQL.instance</code><attribute></attribute></attribute>`
or something like that?

About the [] removal, most of the code already replace it, even in the unsure part, like schema, table, column etc, but not inside the check/where itself
Minor thing i know, but good for consistency :)

**Comment by marco44** [comment]
Yes, there probably are missing attributes. You can try to edit the template in the qq{} areas of the code, to use microsoft's driver. It probably has a few different attributes from the freetds driver… if you find what has to be changed, you can send me a patch…

For the other one, the rest of the code replaces [] correctly, because I parse object names in the rest of the dump, which is quite easy as the object names are easy to identify by their position. In the WHERE clause, it's not really the case. I could maybe have two paths and remove [] when the user asks to not keep case, and put "" instead if case has to be preserved. Will see that tomorrow.

**Comment by McDoit** [comment]
Did a late run tonight with all the fixes, and it worked!!
Havnt enabled any constraints yet as im still working on the unsure sql and then enable it all to see that the data is correct

Adding `<attribute><code>MSSQLUseIntegratedSecurity</code><attribute>false</attribute></attribute>` fixed the main issue with native MSSQL and also editing it too MSSQLNATIVE  to work with that

On a side note, kettle gave me a error when my source DB had a table with ntext column, and mapping it to citext, but i guess it was something to do with kettle itself.

**Comment by marco44** [comment]
I don't have a migration to perform these days (don't even have an sql server database to test on it)… so if you have a diff, or want to do a pull request on this, you are more than welcome.

**Comment by McDoit** [comment]
If i do a pull request, what kind of things do i need to do, except change those things?

**Comment by marco44** [comment]
Nothing. Just report what you changed. Maybe a note in the README explaining that since PDI 7, the SQL Server driver has to be downloaded and installed

**Comment by marco44** [comment]
I just added this commit. Partial indexes should work a bit better if case isn't ignored.
774472497d7801f5bf071ebfabcc0dea12d9f897

**Comment by McDoit** [comment]
Hello

I'm still testing all of it out, and might publish the fix when i get everything sorted out

Sadly i now have an issue with missing rows, can you please take a look at this one?
http://dba.stackexchange.com/questions/165590/postgresql-batch-inserts-fail-silent-randomly

Seems that the count in Kettle is correct but the count differs between Postgres and MSSQL in some cases, i think regarding with the batch size of 100
But kettle doesn't throw any errors around this, and I'm not really sure what can be the cause of it.

**Comment by marco44** [comment]
That's extremely weird… I've been doing dozens of migrations, and would have noticed this I think.

You could try to activate logging of all statements (it will be quite big): put log_min_duration_statement to 0.

Maybe a bug in latest kettle ? all insert threads running truncate on the table, and some doing this while others have started inserting ?

**Comment by McDoit** [comment]
I got it working when I removed the special java step, and connecting the input directly to the output.
What do the java step do?

But your suggestion might be correct, that the table get truncated on all the 8 threads, due to too low latency or too fast computer.

**Comment by McDoit** [comment]
A quick test seems to point to that issue!
Well thought of, thank you!

So the best would be if i can in some way create a step before the first "table input" which truncates the table, and disable it on the 8x table outputs?

**Comment by marco44** [comment]
The best would be to find the bug in kettle. It's not supposed to do that :)

Or at least, it didn't use to do that. I'll give it a look

**Comment by marco44** [comment]
Well, it's in the docs now, so it must mean that they don't bother to do the truncate in only one thread anymore (or I only imagined that they did): http://wiki.pentaho.com/display/EAI/Table+Output

=> Only solution is to add a step in the transformation, or a SQL statement in the initial job (that would be easier)

I'll give it a look

**Comment by McDoit** [comment]
Thank you, so far i have been running them all manually, when i had a missmatch, but when i run thisfor production purposes it would be good to have that extra step, even if its just for my own version :)

I can fork your project and then try to apply the temp fixes on that on, and if its not a bug in kettle, you can use them on your master?

**Comment by McDoit** [comment]
Ah, missed your answer, thank you!

One benefit to have it in the transformation itself, is to make it a bit easier to re-run just one of these modules (as i did now when troubleshooting the issue)
Then you can just run it again and again, and don't have to remember to run a manual truncate for that specific table

**Comment by marco44** [comment]
Pushed a new commit 6ac4809726c74583f6198ee1875bcc63aace7db4

It should work without error with MS's driver, and changes the transformations to run truncate, and then load data.

**Comment by McDoit** [comment]
Works wonders, really really nice!

But i realized that the 'table output' step still have 'truncate table' checked.
Do you think it wont run because it is already done, or should that be disabled by default on that step?

**Comment by marco44** [comment]
I feel a bit stupid :)

I forgot to disable this. I just pushed a correction.

**Comment by McDoit** [comment]
It worked anyway for me, so i will set this as fixed, but will do a rerun later on to check it out!

Thanks a lot for your work and effort on this!
