### ISSUE TITLE
LOCK_ESCALATION keyword not understood

### ISSUE THREAD

**Issue by mfriedemann** [dalibo/sqlserver2pgsql#58]
Hey,

MSSQL dumps that use LOCK_ESCALATION cause an error:

```
$> perl sqlserver2pgsql/sqlserver2pgsql.pl -conf dbtx.conf 
Line <ALTER TABLE [dbo].[Test] SET (LOCK_ESCALATION = DISABLE)
> (1508) not understood. This is a bug at sqlserver2pgsql/sqlserver2pgsql.pl line 2124, <$file> line 1508.
```

**Comment by marco44** [comment]
Same as for #59: please send me either the dump or a complete section (the complete dump is better, as I will be sure there wont be missing spaces for instance)

**Comment by marco44** [comment]
Please reopen if you have a dump to provide.

Regards
