### ISSUE TITLE
Feature Request: option to snake_case names

### ISSUE THREAD

**Issue by McDoit** [dalibo/sqlserver2pgsql#62]
Hello again

i was thinking if its possible to add an option to snake_case names when transferring to Postgres, as that is the preferred  naming convention in postgres, and makes it easier to read

camelCase -> camel_case
PascalCase -> pascal_case
ForeignKeyID -> foreign_key_id
etc

i found a regex that seems to work on most platforms, but cant test it in perl as the online emulator didnt seem to work correctly with perl.
The only thing is to lowercase the entire string after this and it should be good to go

RegEx: 
([a-z])([A-Z]+)
Replacement:
$1_$2

Check out http://fiddle.re/y5xjcn and try with javascript and add the global flag

**Comment by marco44** [comment]
Yes, it's possible (and quite easy) to implement. But do you have a use case ? The purpose of this tool is to migrate a database from sql server to postgresql with minimal fuss. Changing the name of all objects wont help for this.

So, if you have a use case, please explain it to me, I'll add this feature :)

**Comment by McDoit** [comment]
Apart from looking and working better when writing SQL instead of keeping PascalCase (when you have to double quote everything) or lowercase names (and wondering if caroutletid means CarOutLetId or CarOutletId etc) will transforming it to snake_case make it easier to revert back to sql-server or perform easier comparisons or syncs by other people while still comply to standards.

On top of that, when using a ORM they usually makes it really easy to chose another translator for your entity classes and properties to the database names, see for example
https://github.com/npgsql/npgsql/blob/dev/src/Npgsql/NameTranslation/NpgsqlSnakeCaseNameTranslator.cs

Hope it was a good enough case!

**Comment by marco44** [comment]
Yes. Patch is on the way :)

**Comment by marco44** [comment]
2df280e should add this feature. Please tell me

**Comment by McDoit** [comment]
Got this error now when trying to run it:

Use of uninitialized value $string in substitution (s///) at D:\postgres\sqlserver2pgsql.pl line 400.
Use of uninitialized value $string in lc at D:\postgres\sqlserver2pgsql.pl line 401.

**Comment by McDoit** [comment]
It worked with the normal keep indent flag i accidentally used first

**Comment by marco44** [comment]
Yes, this patch made apparent a bug I made a few commits back. Please try with latest version.

**Comment by McDoit** [comment]
Nice with a feature that fixes a bug!

But seems to be working, doing a testrun with it now, inital data and so looks ok

Thank you! 👍

**Comment by marco44** [comment]
I hope it works with kettle, I couldn't test this part
