### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by natha1818** [dalibo/sqlserver2pgsql#63]
When running following command in Windows7:
sqlserver2pgsql.pl -f C:\sqlserver2pgsql-75f8899\files\interfon.sql -b C:\sqlserver2pgsql-75f8899\files\before.txt -a C:\sqlserver2pgsql-75f8899\files\after.txt -u C:\sqlserver2pgsql-75f8899\files\unsure.txt

I get following error message:
Line <CREATE TABLE [dbo].[ABO] (> (1) not understood. This is a bug at C:\sqlserver2pgsql75f8899\sqlserver2pgsql.pl line 2153, <$file> line 1.

What can be the solution?
Thx,
Natha
Attached SQLServer 2000 dump file. (I added txt suffix for upload on GH)
[interfon.sql.txt](https://github.com/dalibo/sqlserver2pgsql/files/964110/interfon.sql.txt)

**Comment by varun-dhawan** [comment]
hi Natha, 
Can you just try removing the "[dbo]" prefix from the table names and then try running the script
Like this --> CREATE TABLE [ABO]

**Comment by natha1818** [comment]
Got same error :

Line <CREATE TABLE [ABO]> (1) not understood. This is a bug at
C:\sqlserver2pgsql-75f8899\sqlserver2pgsql.pl line 2153, <$file> line 1.

**Comment by marco44** [comment]
Sorry, I've been away for a while. The error comes from the fact that your SQL Server dump is a bit different from the dozens I've seen since I started writing this program. I can probably fix this, but I'm curious, how did you get it ? Is it straight from SQL Server ? And exactly what version of SQL Server ?

**Comment by natha1818** [comment]
1.       SQL Server Enterprise Manager -> right-click database -> All
Tasks -> Generate SQL Script

 

2.       SQL Server 2000 Standard Edition (8.00.2039 (SP4))

 

Regards,

Natha

**Comment by marco44** [comment]
Hi,

That's very weird, I've already had quite a few SQL Server 2000 I think, and none had this format.

I'll try to work something out to accept your dump, but it will take a bit of time.

**Comment by marco44** [comment]
I've pushed a bunch of corrections, please tell me if it works now

**Comment by natha1818** [comment]
Works ok now. But… I have added now pk, fk, … and it breaks here:

Line <ALTER TABLE [dbo].[ABO] WITH NOCHECK ADD> (1547) not understood. This is a bug at C:\sqlserver2pgsql-75f8899\sqlserver2pgsql.pl line 2186, <$file> line 1547.

Attached the file I used

Thx a million for everything!!
Natha
[interfon_with_pk.sql.txt](https://github.com/dalibo/sqlserver2pgsql/files/983121/interfon_with_pk.sql.txt)

**Comment by marco44** [comment]
Hi, and sorry for not having answered before. There are quite a few differences in this dump, and this script is getting harder and harder to maintain. We're working with one of my colleagues on rewriting this tool using a real parser… it won't fail anymore with carriage returns and spaces, but it will take some time to finish this. I don't know why your SQL Server doesn't put the carriage returns at the same place as the dozens I've seen until now. I wont fix this issue, I'd rather try the parser way and make the whole thing more robust on the long term.

Sorry about that
