### ISSUE TITLE
MSSQL Timestamp should map to bytea

### ISSUE THREAD

**Issue by mikes-gh** [dalibo/sqlserver2pgsql#64]
When I convert schema from mssql to postgress

Timestamp -> timestamp

They have different meaning in msssql vs postgres

Timestamp should map to bytea

Other wise data migration will fail.

Great tool BTW

**Comment by marco44** [comment]
Yes you're right. I've added rowversion, while I was at it. Thanks a lot.

Solved by 0235c1c1f5f0c8066c964ba4169a46940e5080fd
