### ISSUE TITLE
datetime2 kettle import character varying

### ISSUE THREAD

**Issue by llooz** [dalibo/sqlserver2pgsql#65]
I'm trying to import the data with kettle as explained in the readme but it fails on a table with a datetime2 saying that the column is of type "timestamp without time zone" but the expression uses "character varying".
I think that's something similar to #35

**Comment by marco44** [comment]
Yes that's very similar. I don't have a database with datetime2 data in it, so I don't have anything to test this right now. Maybe you could try just duplicating the date function for datetime2 in the sql_convert_column function ?

**Comment by marco44** [comment]
(if this works, I'll add it)

**Comment by llooz** [comment]
I have done that but i had to also add a jdbc option
`<attribute><code>EXTRA_OPTION_POSTGRESQL.stringtype</code><attribute>unspecified</attribute></attribute>`
This works only partially because as soon the datetime from sql server is null i get the same error

**Comment by llooz** [comment]
I think that i have solved the null problem, it was a bug in the jdbc postgres driver the one included in kettle is very old. I have removed the old one and put "postgresql-42.1.1.jre6.jar" inside the lib directory
