### ISSUE TITLE
Multiple conditions inside check constraint

### ISSUE THREAD

**Issue by jjsantam** [dalibo/sqlserver2pgsql#68]
We have this constraint in SQL Server:

`ALTER TABLE [dbo].[H_DATOS_HIST]  WITH NOCHECK ADD  CONSTRAINT [CKC_KAMIKAZE_H_DATOS_] CHECK  (([KAMIKAZE]>=(0) AND [KAMIKAZE]<=(1)))`

The migrated version is:

`ALTER TABLE "public"."h_datos_hist" ADD CONSTRAINT "ckc_kamikaze_h_datos_" CHECK (kamikaze]>=(0) and [kamikaze<=(1));`

Where the middle square brackets have not been taken into account.

**Comment by marco44** [comment]
Yes. This is produced in the "unsure" file, right ?

**Comment by jjsantam** [comment]
Yes, it is in the "unsure" file.

I have seen similar things with views, but was not sure if in the case of constraints was working as expected.

**Comment by marco44** [comment]
Unsure means these are statements that can't be verified by sqlserver2pgsql. So there will be errors. I didn't write a full SQL parser in the tool, by far. Check constraints, for example, are crudely copied. I only try to remove brackets at the beginning and the end. We have a long term project of rewriting this tool using a more advanced SQL parser, but it wont be before a while.

**Comment by jjsantam** [comment]
Then I hope you will get some objects moving from "unsure" to "before" or "after in the future. The effort is appreciated.

If you what any more feedback, I will be working with the tool on another couple of databases.

**Comment by marco44** [comment]
Yes, writing a parser is for this purpose

**Comment by marco44** [comment]
Closing, as I cannot do anything for you for now

**Comment by tfredy2** [comment]
Hello @marco44  and @jjsantam I has the same problem, what i did was delete the brackets
example: 

Original:
ALTER TABLE "public"."h_datos_hist" ADD CONSTRAINT "ckc_kamikaze_h_datos_" CHECK (kamikaze]>=(0) and [kamikaze<=(1));

Modified:
**ALTER TABLE "public"."h_datos_hist" ADD CONSTRAINT "ckc_kamikaze_h_datos_" CHECK (kamikaze>=(0) and kamikaze<=(1));**

my database is from 2500 tables and apparently it's works well for me, I hope for you too.
See you.
