### ISSUE TITLE
Error parsing input file

### ISSUE THREAD

**Issue by pmpetit** [dalibo/sqlserver2pgsql#71]
Hello, 
i probably did something wrong, but it did this basic test :
in the input file test.sql
CREATE TABLE dbo.ac_data (timestart bigint NOT NULL,
  timeend bigint NOT NULL,
  diagnosestart bigint NULL,
  diagnoseend bigint NULL,
  records varbinary(max) NULL,
  numbytes bigint NULL,
  description varbinary(max) NULL,
  numdescriptionbytes int NOT NULL,
  store_id int NOT NULL,
  valid int NULL,
  version varchar(25) NULL,
  transient int NOT NULL DEFAULT ((0)),
  CONSTRAINT PK_ac_data PRIMARY KEY CLUSTERED
    (
      store_id ASC,
      timestart ASC,
      timeend ASC,
      transient ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON PRIMARY
) ON PRIMARY TEXTIMAGE_ON PRIMARY

/sqlserver2pgsql.pl -f /tmp/test.sql -b /tmp/before.sql -a /tmp/after.sql -u /tmp/unsure.sql
Line <CREATE TABLE dbo.ac_data (timestart bigint NOT NULL,
> (1) not understood. This is a bug at ./sqlserver2pgsql.pl line 2256, <$file> line 1.
 
i do not find what is wrong....

thanks

**Comment by marco44** [comment]
There are no brackets surrounding objets names. This is very suspicious… where does this SQL file come from ?

**Comment by pmpetit** [comment]
there was some bracket, i removed them for testing...
i thought it was the problem
this script comes from an export (generate script from mssql)

**Comment by marco44** [comment]
You mustn't touch the produced script. Please try again without any modification.

**Comment by pmpetit** [comment]
it is the same , that's why i removed brackets

**Comment by pmpetit** [comment]
so the with the unmodified file : 
WARNING: the source database is set as ARITHABORT OFF.
         It means that for SQL Server, 10/0 = NULL.
         You'll probably have problems porting that to PostgreSQL.
Cannot understand   [timestart] [bigint] NOT NULL,

 at ./sqlserver2pgsql.pl line 1463, <$file> line 93.
	main::parse_dump() called at ./sqlserver2pgsql.pl line 2901

**Comment by marco44** [comment]
So it's not the same…

It fails somewhere else.

Send me the sql dump at cousinmarc at gmail dot com if you want me to solve this fast…

**Comment by pmpetit** [comment]
with this file 
[test.zip](https://github.com/dalibo/sqlserver2pgsql/files/1298911/test.zip)

Cannot understand   [id] [int] NOT NULL,

 at ./sqlserver2pgsql.pl line 1463, <$file> line 2.
	main::parse_dump() called at ./sqlserver2pgsql.pl line 2901

**Comment by marco44** [comment]
That's weird… most of what is usually tabs in the dump is replaced with two spaces in your file. Are you sure it comes directly from SQL Server (not edited by hand). And I notice it isn't in UTF16 encoding… is there an option when exporting ?

**Comment by pmpetit** [comment]
let me describe the context :

my workstation is a fedora 26 distrib.

my production server is a aws europe server, i connect from my workstation
to the windows server using remmina and tunneling through port 3389 and a
gateway

when i log on the win$, i must use the graphical keyboard (because of
qwert/azerty pb on the prod server)

then i start sql management studio and generate the script file.

i copy paste the ddl sql code from it (i think the pb is here)

So, i am goint to copy the output file to my gateway and then to my
workstation (using winscp or something like that)

i keep you informed....


thanks for your check.






*Pierre-Marie PETIT*
SI Engineer
Tech & Talents - B'TWIN

*+33 6 48 26 78 93Check our new
website: https://techandtalents.subsidia.org/
<https://techandtalents.subsidia.org/>*

**Comment by pmpetit** [comment]
For your information, oracle and sqldeveloper have a great migration
project tool.

It is very easy to migrate a sqlserver schema to an oracle instance.

it also very easy to migrate this new oracle schema to pgsql using
ora2pg....
.
and with 1 godengate on the oracle and 1 goldengate on pgsql, data comes
easily too....


but i am still testing sqlserver to pg, to make it usefull.





*Pierre-Marie PETIT*
SI Engineer
Tech & Talents - B'TWIN

*+33 6 48 26 78 93Check our new
website: https://techandtalents.subsidia.org/
<https://techandtalents.subsidia.org/>*

**Comment by marco44** [comment]
The copy and paste will probably have destroyed the formatting.

**Comment by pmpetit** [comment]
it was just a formatting pb in the source file cr where remplaced with 2 spaces

**Comment by pmpetit** [comment]
i closed the issue




*Pierre-Marie PETIT*
SI Engineer
Tech & Talents - B'TWIN

*+33 6 48 26 78 93Check our new
website: https://techandtalents.subsidia.org/
<https://techandtalents.subsidia.org/>*

**Comment by tfredy2** [comment]
I cannot understand you solution.

I've the same problem but my solution  was next:

**ALTER TABLE [dbo].[table_name] ADD** CONSTRAINT [name_constraint] PRIMARY KEY CLUSTERED.

in line the file generated by sql management
