### ISSUE TITLE
Syntax not supported

### ISSUE THREAD

**Issue by frost242** [dalibo/sqlserver2pgsql#74]
Hello,

I have a problem while parsing a dump file on the following statement:

> 
> ALTER TABLE [dbo].[Table] WITH NOCHECK ADD
>         CONSTRAINT [PK_Table] PRIMARY KEY  CLUSTERED
>         (
>                 [intIdentifiant]
>         ) WITH  FILLFACTOR = 90  ON [PRIMARY]
> GO

**Comment by madtibo** [comment]
Hello,

It's been quite some time and I hope you still have the dump somewhere...

Does the `ALTER TABLE (...) KEY CLUSTERED` on 1 or 2 lines ?
Could you give the exact error message?

**Comment by madtibo** [comment]
Could you try using the correction from branch issue_74: 7988448c2d89018af1626ef1a195acb960b676a8
Does it solve your problem?
