### ISSUE TITLE
Check Constraint

### ISSUE THREAD

**Issue by tfredy2** [dalibo/sqlserver2pgsql#75]
I'm using  script and works great, but have a problem with the check constraints to the generate them but example:
Sql Server:
ALTER TABLE [dbo].[name_table] WITH CHECK ADD CONSTRAINT [FOLIO] CHECK (([NUM_FOLIO]>=(0) AND [NUM_FOLIO]<=(999999)))

The check constraint generate by tool:
ALTER TABLE "public"."name_table" ADD CONSTRAINT "folio" CHECK (num_folio]>=(0) AND [num_folio<=(999999));

The only Solution that found was delete the brackets with a replace with notepad++.
I have tried to modify the tool but sometimes have a error or convert to uppercase.
There would be some way to remove the brackets when generating the file?
I hope can help me.

I hope response.
Thank in advance.

**Comment by ashu202** [comment]
Got same kind of error near "Check Constraints". Below is the error. First line is my command (in italic), 2nd is the error in sql dump. 3rd is the line number in "sqlserver2pgsql.pl" file.

_C:\Users\ADMIN\Downloads\SqlServer_postgres\sqlserver2pgsql>perl sqlserver2pgsql.pl -f catch_script.sql -b outb -a outa -u outu_

> Line <ALTER TABLE [dbo].[AverageMonthlyHouseholdIncomeTypes]  WITH NOCHECK ADD  CONSTRAINT [repl_identity_range_18B2CF9A_0EED_491F_9196_4E4017449B13] CHECK NOT FOR REPLICATION (([AverageMonthlyHouseholdIncomeTypeId]>(23580007) AND [AverageMonthlyHouseholdIncomeTypeId]<=(23581007) OR [AverageMonthlyHouseholdIncomeTypeId]>(23581007) AND [AverageMonthlyHouseholdIncomeTypeId]<=(23582007)))


> **(2444) not understood. This is a bug at sqlserver2pgsql.pl line 2256, <$file> line 2444.** 

Please help me.
Thanks in advance.

**Comment by madtibo** [comment]
Merged in c506f7e4274
