### ISSUE TITLE
(almost) Not an issue

### ISSUE THREAD

**Issue by Maxzor** [dalibo/sqlserver2pgsql#86]
Hello,
Just chiming in to say that your project has saved hours of my time doing semi-amateur db archaeology, big thank you, it rocks!

I had a few lines with disabled indexes that were considered as bugs i.e. :
ALTER INDEX [HFMNLTL2] ON [reflex].[HFMNLTP] DISABLE

Forgive me I am too bad at perl for a pull request :/
Ah also maybe move this on gitlab? now that github and sqlserver... well you know ;)
I owe you some beers, BR, Maxime

**Comment by madtibo** [comment]
Hello Maxime,
Thanks for the information!

I'll check if there is an easy way to get the corresponding index commented in the PostgreSQL schema file.
Otherwise, I will just skip the line.

For the beer, it would be a pleasure, unless @marco44 finds you before  :-)

**Comment by marco44** [comment]
Oh, by the way, weird objects go to the unsure file. It's better than to skip them.

**Comment by madtibo** [comment]
Thank you for the tip... and the hypothetical beer ;-)

**Comment by madtibo** [comment]
@Maxzor I pushed a correction in branch disabled_indexes. Does it work for you?

**Comment by Maxzor** [comment]
@madtibo yes, thanks, you can merge.
I am now loosing hair on kettle,
The ETL crashed after first table oO, might end up regexing the data dump :)

**Comment by madtibo** [comment]
@Maxzor 
I never used pgloader so I won't be able to help you on this one.

About kettle, you have the error : 
```
2018/06/26 01:24:00 - Table output.3 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Unexpected batch update error committing the database connection.
```

Can you check that your MSSQL connection options are correct? The same for the PostgreSQL connections options?
If they are right, maybe have a look into the databases logs if there is any clue about why the connection is not functional?

PS : if you are in Paris, save the date for the 10th pgsession on week 47, maybe there will be some beers around  ;-)

**Comment by marco44** [comment]
From experience on the error, it's probably a typing problem. If it's the case, you'll have the complete error in the PG log

**Comment by madtibo** [comment]
@Maxzor has your problem been solved?
