### ISSUE TITLE
PG 11 revisit Stored procedure conversion

### ISSUE THREAD

**Issue by mikes-gh** [dalibo/sqlserver2pgsql#88]
Now that postgres 11 (still beta) is supporting stored procedures it may be possible to convert these too.
I looked at the syntax and it seems very similar.  It seems this feature is specifically designed to help MSSQL users migrate to postgres.  The differences are going to be in pgSQL vs TSQL.  The CREATE PROCEDURE ALTER PROCEDURE etc all look good to go.

Personally I think logic should be kept out of the database but I have lots of excel sheets vb6 programs I wrote many years ago that rely on them so I dont have much choice but to keep supporting them.,.

**Comment by madtibo** [comment]
Hello Mike,

Thank you for this information.
Unfortunately, migrating TSQL to pgSQL is a very big project. This project is currently not supporting  it (in the README : "It won't migrate PL procedures, the languages are too different."). And there is no plan to support it in the future.
You are of course more than welcome to start working on it  :-)

Cheers,
Thibaut

**Comment by mikes-gh** [comment]
I am nearing completion of a mssql to postgres migration
Having converted several queries from TSQL to pgSQL I can see this is not really achievable in the scope of this project so I am closing this
