### ISSUE TITLE
Add option to remove MSSQL timestamp/rowversion columns when converting

### ISSUE THREAD

**Issue by mikes-gh** [dalibo/sqlserver2pgsql#89]
postgres has xmin for this purpose.

currently I remove the columns after database creation

**Comment by mikes-gh** [comment]
This is what I am doing but it relies on column naming

./sqlserver2pgsql.pl -b before.sql -a after.sql -u unsure.sql -f aescreate.sql

perl -0777 -i.original -pe 's|,\n\t"timestamp" bytea NOT NULL||g' /home/postgres/before.sql
perl -0777 -i.original -pe 's|,\n\t"timestamp" bytea||g' /home/postgres/before.sql
perl -0777 -i.original -pe 's|,\n\t"rowversion" bytea||g' /home/postgres/before.sql
perl -0777 -i.original -pe 's|,\n\t"rowversion" bytea NOT NULL||g' /home/postgres/before.sql

**Comment by madtibo** [comment]
hi @mikes-gh,
I added a new `-drop_rowversion` switch for this. It is available in #100 
Is it doing what you had in mind?
Cordialement,

**Comment by madtibo** [comment]
The option is now available.
Close this issue.

**Comment by mikes-gh** [comment]
Thank you  sorry for not responding earlier.  Still using the script on a weekly basis,
I currently don't drop the timestamps so didn't have time to test.
But I will be so will post back if there is any issue.

**Comment by madtibo** [comment]
@mikes-gh great  :+1:

**Comment by mikes-gh** [comment]
Very Very late response.
I finally started using this option.  Its great because it gets rid on a large section of my script where I drop all the timestamps.
The reason I was finally kicked into using the fix is beacuase I added a table in the sourcer db and forgot to drop the timestamp column after migration.

With your option I no longer have to remeber.

Thankyou

**Comment by madtibo** [comment]
thank you for your feedback!
