### ISSUE TITLE
No check length constraint added for binary data

### ISSUE THREAD

**Issue by McDoit** [dalibo/sqlserver2pgsql#91]
Hello

I have a couple of columns storing hash values with a specific length and then being part of the primary key
The script simply ignores the length set, while in the case of text columns a check constraint is created with the length from the sql server column
Best would be to have the same behavior for the new bytea columns, with a check constraint in the before file
If that is a bit harder, something in the unsure file maybe?

Thank you for a really nice script!

**Comment by madtibo** [comment]
Hello McDoit,

Could you please provide a sample table definition so that I can test your case more easily?

Cheers,

**Comment by McDoit** [comment]
Will this suffice?

/****** Object:  Table [candidate].[PersonalIdentityHashes]    Script Date: 2018-07-17 13:16:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [candidate].[PersonalIdentityHashes](
	[OrganizationId] [int] NOT NULL,
	[PersonalIdentityHash] [binary](64) NOT NULL,
	[CandidateId] [bigint] NOT NULL,
 CONSTRAINT [PK_candidatePersonalIdentityHashes] PRIMARY KEY CLUSTERED 
(
	[OrganizationId] ASC,
	[PersonalIdentityHash] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO

**Comment by madtibo** [comment]
Hello @McDoit ,
The script fails on the ` [PersonalIdentityHash] binary NOT NULL,` line. Shouldn't the 'binary' column type be enclosed by brackets?
Then, from your script, I do not see a reference to a column size, is it normal?
Cheers,

**Comment by McDoit** [comment]
Yes it does, seems like the `[binary](64)` combination is interpreted by github into [binary](64)

**Comment by madtibo** [comment]
@McDoit OK, good news!
can I mark this issue as solved?

**Comment by madtibo** [comment]
OK, got the idea for your problem.
Could you check if the 91_binary_check_length branch solve your issue?

**Comment by madtibo** [comment]
branch merged
