### ISSUE TITLE
create table [00_P_Process_Time_Window]:  (36) not understood.

### ISSUE THREAD

**Issue by tfossoul** [dalibo/sqlserver2pgsql#97]
Hi,

I hope someone could help me. I'm probably missing a stupid think but i don't see it :/.

The code on the Microsoft SQL file:
```
create table [00_P_Process_Time_Window] (
	Nbr_Month_ToProcess smallint not null,
	Record_Update_TS smalldatetime DEFAULT (getdate()) NOT NULL
);
```
The command:
sudo sqlserver2pgsql/sqlserver2pgsql.pl -f ~/Test_Tables_v1.1.sql   \
                     -b ~/output_before_script.txt \
                     -a ~/output_after_script.txt  \
                     -u ~/output_unsure_script.txt

Here is the error:
```
Line <create table [00_P_Process_Time_Window] (
> (36) not understood. This is a bug at sqlserver2pgsql/sqlserver2pgsql.pl line 2339, <$file> line 36.
```

I did an apt-get update & upgrade.

Thanks in advance

**Comment by beaud76** [comment]
Hi tfossoul,
It seems that in your statement the table name is not prefixed by its schema name. You should at least have something like a "CREATE TABLE [dbo].[00_P_Process_Time_Window] (".
How have you generated the input sql dump ? Have you followed the procedure described in the documentation ?
Best regards.

**Comment by madtibo** [comment]
You must use a Sql Server database dump and not a user script in order to migrate your schema.
I close this issue.
